### DISCUSSION TITLE
getting error in ref pull stage

### DISCUSSION THREAD

**Discussion by hiyamandal** [mvisonneau/gitlab-ci-pipelines-exporter#660] [Q&A]
`WARN[2023-05-30T12:36:25Z] pulling refs from project                     error="Get \"https://gitlab.---------.com/api/v4/projects/596/repository/branches?page=1&per_page=100\": dial tcp 192.168.63.93:443: i/o timeout"`
 
This is the error I am getting while running the exporter. 
 I tried opening the URL manually and it works without the "page=1&per_page=100\" string at the end. I defined the specific branch name in the config file also so that it only look up for the main branch.. still the error is the same

config file: 
```
project_defaults:
    refs:
      branches:
        # Monitor pipelines related to project branches 
        # (optional, default: true)
        enabled: true

        # Filter for branches to include
        # (optional, default: "^main|master$" -- main/master branches)
        regexp: "^main|master$"
```

Can you please help me resolve this error? 
For context: I am installing on remote ubuntu server
