### ISSUE TITLE
Duplicate metrics with HA setups

### ISSUE THREAD

**Issue by laimis9133** [mvisonneau/gitlab-ci-pipelines-exporter#1001]
Hi all,
First of all thanks for this great project! 
I wanted to ask if anyone has ever faced similar issues when metrics for the same project/reference get duplicated in a HA setup running more than 1 exporter? 
I'm running a Kubernetes Helm deployment via ArgoCD (chart version: `0.3.5`, app version: `v0.5.10`) and set my values.yaml to have 2 replicas:

```yaml
gitlab-ci-pipelines-exporter:
  gitlabSecret: "gitlab-ci-pipelines-exporter-secret"
  podAnnotations:
    fluentbit.io/exclude: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
  
  redis:
    persistence:
      enabled: true

  replicas: 2            #  Setup of 2 exporter pod replicas
 
  resources:
    ...

```

This works fine, however my metrics get duplicated because of 2 pods exporting these metrics:

<img width="1735" alt="Image" src="https://github.com/user-attachments/assets/16fa5568-d82c-44b9-84bd-f830c78c3f53" />
  

Increasing the value to `replicas: 4` results in 4 times of the same metric:

<img width="1737" alt="Image" src="https://github.com/user-attachments/assets/3b457bd3-ffd3-455b-adb4-76523051612b" />

I understand this might come from the very nature on how Prometheus is set-up here (to include `k8s_pod_name`), however I'm a bit confused  how are these metrics get exposed in a HA setup. The ref/project discovery seems to be more or less distributed across each exporter, however should exported metrics also be bound to a single pod and not "shared" amongst all of the replicas in that case?  
Any advice from people using HA on how to overcome this? Or should I address how Prometheus is setup here?

To avoid duplication I'm running a single beefy replica for the time being.
