### ISSUE TITLE
Wildcards not fetch all branchs

### ISSUE THREAD

**Issue by agferronato** [mvisonneau/gitlab-ci-pipelines-exporter#104]
According documentation

https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/master/chart/values.yaml

i try to use refs from [Value.yaml](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/master/chart/values.yaml)

refs: ".*"

And the [Syntax Configuration](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/master/docs/configuration_syntax.md
)
it's refs_regexp: ".*"

But only come master branch.

My values.yaml
```


 config:
   gitlab:
     url: https://git.company
     # You can also configure the token using --gitlab-token
     # or the $GCPE_GITLAB_TOKEN environment variable
     token: mytoken
   polling_workers: 5
 
   wildcards:
     - refs: ".*"
 
```

I try the same used on this [issue](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/issues/84)
Thanks

**Comment by mvisonneau** [comment]
:wave: hey @agferronato,

I updated the example in the default chart values which was indeed still referring to the old syntax. There is a complete syntax reference available here: 

https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/master/docs/configuration_syntax.md

I reckon that you now must configure a `group` or a `user` on your wildcard:

```yaml
wildcards:
  - owner: # Will fetch all the projects of group 'foo'
      name: foo
      kind: group
    refs_regexp: ".*" # Will fetch all the branches/tags/MRs of discovered projects
```

Let me know if this sorts your issue out :)
