### ISSUE TITLE
Token not being fetched correctly

### ISSUE THREAD

**Issue by joao-p-marques** [mvisonneau/gitlab-ci-pipelines-exporter#113]
When I try to setup the application using docker and the config file:
```
config:
  gitlab:
    url: https://gitlab.com
    token: <MY_TOKEN>
```
The app does not work, and returns a 404 when trying to fetch data from GitLab API (same error as when the token is wrong).

However, if I pass the same token through the command line:
```
docker run -d --name gitlab-ci-pipelines-exporter -v $(pwd)/gitlab-ci-pipelines-exporter/config.yml:/etc/config.yml -p 8888:8080 mvisonneau/gitlab-ci-pipelines-exporter:latest --config /etc/config.yml --gitlab-token <MY_TOKEN>
```
It works as expected.

Why is the token not being fetched correctly? Am I doing the config wrong?

**Comment by xt99** [comment]
Same thing for me also

**Comment by mvisonneau** [comment]
:wave: I tried to reproduce the bug using the `master` branch and I was not able to.
Which versions are you using @joao-p-marques @xt99 ? 🤔

**Comment by mvisonneau** [comment]
Have you got any special characters that could be misinterpolated from yaml?
To double check, the `<` `>` are not expected in the syntax:

```yaml
gitlab:
  url: https://gitlab.com
  token: 'XxXxXxxxXxxXxx'
```
