### ISSUE TITLE
taskq hangs the app in version 0.4.0

### ISSUE THREAD

**Issue by lokenorlinjohannessen** [mvisonneau/gitlab-ci-pipelines-exporter#154]
## Problem
I upgraded gitlab-ci-pipelines-exporter from 0.3.3 to 0.4.0, and now it "hangs" when trying to PullProjectRefsFromProjects

I have a little over 1100 projects, so that might be part of the reason ( But it worked fine in 0.3.3 )

## Error
```go
created by github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter.schedulePullProjectRefsFromProjects
	github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter/scheduler.go:120 +0x398
goroutine 188439 [chan send, 51 minutes]:
github.com/vmihailenco/taskq/v3.(*Consumer).Add(...)
	github.com/vmihailenco/taskq/v3@v3.0.0/consumer.go:144
github.com/vmihailenco/taskq/v3/memqueue.(*Queue).enqueueMessage(0xc0002240c0, 0xc007c2f790, 0xc009662d00, 0xc009662d50)
	github.com/vmihailenco/taskq/v3@v3.0.0/memqueue/queue.go:209 +0x13d
github.com/vmihailenco/taskq/v3/memqueue.(*Queue).Add(0xc0002240c0, 0xc007c2f790, 0xc67d40, 0xc007d70240)
	github.com/vmihailenco/taskq/v3@v3.0.0/memqueue/queue.go:184 +0xdd
github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter.schedulePullProjectRefsFromProject(0xdfc560, 0xc000292000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter/scheduler.go:166 +0x183
created by github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter.schedulePullProjectRefsFromProjects
	github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter/scheduler.go:120 +0x398
goroutine 188440 [chan send, 51 minutes]:
```

**Comment by mvisonneau** [comment]
👋 hey @lokenorlinjohannessen, thanks for reporting this issue!

Am I right to assume that the logs you provided are from the profiling endpoint? 🤔 
Does it happen right away or after a while?

**Comment by lokenorlinjohannessen** [comment]
@mvisonneau actually the logs are directly from STDOUT.
It took roughly around 6hours before it started to hang.

Config I used:
```
gitlab:
  url: https://XXX
defaults:
  fetch_pipeline_job_metrics: true
  output_sparse_status_metrics: true
  refs_regexp: '.*'
  fetch_merge_request_pipelines_refs: true
  output_sparse_status_metrics: true
wildcards:
  - owner:
      name: XXX
      kind: group
  - owner:
      name: XXX
      kind: group
  - owner:
      name: XXX
      kind: group
      include_subgroups: true
  - owner:
      name: XXX
      kind: group
  - owner:
      name: XXX
      kind: group
      include_subgroups: true
  - owner:
      name: XXX
      kind: group

```
