### ISSUE TITLE
Flag --listen-address not working in 0.4.0

### ISSUE THREAD

**Issue by mhollstein** [mvisonneau/gitlab-ci-pipelines-exporter#155]
Try to start exporter version 0.4.0 with --listen-address ":8085" results in an error:
flag provided but not defined: -listen-address

Command-Line:
sudo ./gitlab-ci-pipelines-exporter --config ./config.yml  --listen-address ":8085"

**Comment by mvisonneau** [comment]
👋 hey @mhollstein,

indeed this flag has been removed in favor of an in config definition:

```yaml
# config.yml
server:
  listen_address: ':8085'
```
