### ISSUE TITLE
[helm] gitlab_ci_pipeline_last_run_status empty

### ISSUE THREAD

**Issue by T1loc** [mvisonneau/gitlab-ci-pipelines-exporter#165]
Hello,

I have some difficulty obtaining the values for gitlab_ci_pipeline_last_run_status
Running a curl inside the container doesn't return an output :

```
curl -s gitlab-ci-pipelines-exporter:8080/metrics | grep run
```

But I'm getting others values : 
```
curl -s gitlab-ci-pipelines-exporter:8080/metrics | wc -l
22087
```

My config file : 

```
---
config:
  gitlab:
    url: https://gitlab.com
  projects:
    - name: xxx
  project_defaults:
    pull:
      refs:
        regexp: ".*"
serviceMonitor:
  enabled: true
```

If you have any ideas :-)
