### ISSUE TITLE
Dynamically fetch projects by path and namespace

### ISSUE THREAD

**Issue by TalShlomiNielsen** [mvisonneau/gitlab-ci-pipelines-exporter#175]
I'm trying to use gitlab-ci-pipeline-exporter helm chart in order to fetch all our repositories in Gitlab and I was not able to fetch by path. for example I want to fetch all the repositories under test group, https://gitlab.com/tal.shlomi/test.

I tried to use wildcards and search but it seems not to answer my requirement.
thank you

**Comment by mvisonneau** [comment]
👋 hey @TalShlomiNielsen, would you mind sharing a sanitized version of the config file you tried to use? At first sight, assuming that `tal.shlomi/test` is a valid group on which your token has sufficient accesses upon, it seems that something around those lines should be what you need:

```yaml
wildcards:
  - owner:
      name: tal.shlomi/test
      kind: group
```

**Comment by TalShlomiNielsen** [comment]
@mvisonneau thanks for your answer. none of the configurations that I tried succeeded, so I don't have any real examples to show, but I can explain more about my requirements; I have for example 30 repositories and one sub-group with 5 repositories under https://gitlab.com/tal.shlomi/test, I want to fetch all these repositories dynamically so I need to use the wildcards. Also I want to be able to fetch new repositories under the same group without changing the configuration, I mean I don't want to add new line in the projects section for each new repository.
Thanks in advance

**Comment by mvisonneau** [comment]
what about this? 🤔 

```yaml
wildcards:
  - owner:
      name: tal.shlomi/test
      kind: group
      include_subgroups: true
```

**Comment by TalShlomiNielsen** [comment]
@mvisonneau  I tried to use 
`config:
  gitlab:
    url: https://gitlab.com
    token: <token>
  wildcards:
    - owner:
        name: tal.shlomi/test
        kind: group`

**Comment by mvisonneau** [comment]
if you want to validate that your token actually works, you can use this global wildcard which will attempt to get all the possible projects:

```yaml
wildcards: [{}]
```

https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/main/docs/configuration_syntax.md#pull-all-projects-accessible-by-the-provided-token

**Comment by TalShlomiNielsen** [comment]
@mvisonneau It works with this flag include_subgroups: true thanks! how can I fetch few groups? I mean another owner

**Comment by mvisonneau** [comment]
great!

```yaml
wildcards:
  - owner: { name: group1, kind: group, include_subgroups: true }
  - owner: { name: group2, kind: group, include_subgroups: true }
```
