### ISSUE TITLE
wildcard fetch every branch refs

### ISSUE THREAD

**Issue by TalShlomiNielsen** [mvisonneau/gitlab-ci-pipelines-exporter#177]
hey @mvisonneau , I'm trying to fetch all the branches of my repositories using this config , but the exporter does not fetch anything

```yaml
wildcards:
    - owner: { name: tal/test, kind: group, include_subgroups: true }
    - owner: { name: tal/dev, kind: group, include_subgroups: true }
    - pull:
        refs:
          regexp: ".*"
          from:
            merge_requests:
              enabled: true
```

thanks again for the help!

**Comment by mvisonneau** [comment]
this should be better:

```yaml
project_defaults:
  pull:
    refs:
      regexp: ".*"
    from:
      merge_requests:
        enabled: true

wildcards:
  - owner: { name: tal/test, kind: group, include_subgroups: true }
  - owner: { name: tal/dev, kind: group, include_subgroups: true } 
```

**Comment by mvisonneau** [comment]
if you want to do it on a per wildcard basis it would have to look like this:

```yaml
wildcards:
  - owner:
       name: tal/test
       kind: group
       include_subgroups: true
    pull:
      refs:
        regexp: ".*"
      from:
        merge_requests:
          enabled: true

  - owner:
       name: tal/dev
       kind: group
       include_subgroups: true
    pull:
      refs:
        regexp: ".*"
      from:
        merge_requests:
          enabled: true
```
