### ISSUE TITLE
time="2020-11-11T15:45:02Z" level=error msg="couldn't open config file : open /etc/gitlab-ci-pipelines-exporter/config.yml: permission denied"

### ISSUE THREAD

**Issue by RPenswick** [mvisonneau/gitlab-ci-pipelines-exporter#180]
Hi, 

First post so I sincerly hope this is the correct way to ask for assistance. 

I am loving the look of this tool and its potential, perfect for what I am working. I just cant get it working on my instance. 

Once I got past /tmp exec and some firewald issues I am getting this error when trying to run the Docker-Compose. 

```time="2020-11-11T15:45:02Z" level=error msg="couldn't open config file : open /etc/gitlab-ci-pipelines-exporter/config.yml: permission denied"```

Is anyone able to give me some guidance as to next steps? 

Im using the default `Docker-compose.yml` 

`/gitlab-ci-pipelines-exporter/config.yml` is 
```
gitlab:
  url: https://gitlab.xxxxxxxxxx/
  token: Axxxxxxxxxxxxxxxx4

# Pull jobs related metrics on all projects
project_defaults:
  pull:
    pipeline:
      jobs:
        enabled: true

# Example public projects to monitor
projects:
  - name: gitlab-org/gitlab-runner
    # Pull environments related metrics prefixed with 'stable' for this project
    pull:
      environments:
        enabled: true
        name_regexp: '^stable.*'

  - name: gitlab-org/charts/auto-deploy-app
```

Any help would be fantastic, going slightly mad trying to understand the error. 

thanks, 

Richard
