### ISSUE TITLE
jobs are not fetched occasionally 

### ISSUE THREAD

**Issue by TalShlomiNielsen** [mvisonneau/gitlab-ci-pipelines-exporter#183]
Hey @mvisonneau , I'm trying to fetch Jobs as you recommended. During the fetching lot's of jobs that are running are not being fetched. this is my configuration:
```
config:
  gitlab:
    url: https://gitlab.com
    token: <token>
  wildcards:
    - owner:
         name: tal.shlomi/test
         kind: group
         include_subgroups: true
      pull:
        refs:
          regexp: ".*"
        pipeline:
          jobs:
            enabled: true
```

and this is some warning I see in the logs:
`"level":"warning","msg":"found some project ref jobs but did not manage to refresh all jobs which were in memory"`

What can be done ?
Thanks!
