### ISSUE TITLE
Jobs not working with webhook

### ISSUE THREAD

**Issue by 190ba** [mvisonneau/gitlab-ci-pipelines-exporter#184]
Hey @mvisonneau,

First, thank you for this great project :)

I'm currently facing an issue with a configuration with Gitlab sending webhooks to the exporter, hosted in AKS
Pipeline events are correctly,exported, though i'm not sure whether they are pushed or pulled :
`{"environments-count":0,"level":"info","msg":"scheduling metrics pull","refs-count":60,"time":"2020-11-20T16:16:05Z"}`

Regarding the Job events, I have these errors in the logs, and no metrics showing in Grafana
`{"event-type":"*gitlab.JobEvent","ip-address":"10.1.0.67:43490","level":"warning","msg":"received a non supported event type as a webhook","time":"2020-11-20T16:15:37Z","user-agent":""}`

Here is the conf I used :

```
  gitlab:
    url: https://gitlab.blablabla

    token: "{{ gitlab__token }}"
  wildcards:
      owner:
        name: me
        kind: user
        include_subgroups: true
      pull:
      refs:
        regexp: ".*"
      pipeline:
        jobs:
          enabled: true
```

Could you help me on this part please ?
And could you confirm the "pull" section in configuration file also apply to webhook ?

Thanks a lot
Regards
Igor

**Comment by mvisonneau** [comment]
Hey @190ba, thank you for the kind feedback! 🙇 

Regarding your issue, indeed, only pipeline and deployment events are supported. Even if you want/need jobs metrics, using pipeline events will be good enough as they are generated on each job changes. 

In your config, the only thing supplementary required in order to get push support is the following:

```yaml
server:
  webhook:
    enabled: true
    secret_token: <strong_arbitrary_secret_token>

wildcards / projects matching the ones expected to send events
``` 

hope this helps!

**Comment by mvisonneau** [comment]
the example config is a good start actually: https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/main/examples/webhooks/gitlab-ci-pipelines-exporter/config.yml

**Comment by mvisonneau** [comment]
I assume that your problem is solved @190ba, feel free to reopen if necessary 👍

**Comment by strowi** [comment]
Hi,

sorry to reopen, but it seems i'm running into the same issue with v0.4.6. Webhook works, but metrics-pull still gets scheduled..?

```yaml
server:
  webhook:
    enabled: true
    secret_token: xyz=

gitlab:
  url: https://git.xyz.net

wildcards:
  - owner:
      name: sys
      kind: group
      include_subgroups: true
    pull:
    refs:
      regexp: ".*"
    pipeline:
      jobs:
        enabled: true
```
gives the following logs:
```
gitlab-ci-exporter_1  | time="2021-01-27T20:56:39Z" level=info msg="exporter configured" gitlab-endpoint="https://git.xyz.net" pull-environments-from-projects-interval=1800s pull-metrics-interval=30s pull-projects-from-wildcards-interval=1800s pull-rate-limit=10rps pull-refs-from-projects-interval=300s
gitlab-ci-exporter_1  | time="2021-01-27T20:56:39Z" level=info msg="scheduling projects from wildcards pull" wildcards-count=1
gitlab-ci-exporter_1  | time="2021-01-27T20:56:39Z" level=info msg="scheduling environments from projects pull" projects-count=0
gitlab-ci-exporter_1  | time="2021-01-27T20:56:39Z" level=info msg="scheduling refs from projects pull" projects-count=0
gitlab-ci-exporter_1  | time="2021-01-27T20:56:39Z" level=info msg="scheduling metrics pull" environments-count=0 refs-count=0
gitlab-ci-exporter_1  | time="2021-01-27T20:56:39Z" level=info msg="http server started" listen-address=":8080" metrics-endpoint-enabled=true pprof-endpoint-enabled=false webhook-endpoint-enabled=true
gitlab-ci-exporter_1  | time="2021-01-27T20:56:45Z" level=info msg="discovered new project" project-name=sys/renovate wildcard-archived=false wildcard-owner-include-subgroups=true wildcard-owner-kind=group wildcard-owner-name=sys wildcard-search=
...
gitlab-ci-exporter_1  | time="2021-01-27T20:59:34Z" level=info msg="scheduling metrics pull" environments-count=0 refs-count=5
```

regards,
strowi

**Comment by mvisonneau** [comment]
👋 hey @strowi,

indeed, apologies if this is unclear, basically if you want to disable the pull, you will need to add the following to your config:

```yaml
pull:
  projects_from_wildcards:
    on_init: false
    scheduled: false

  environments_from_projects:
    on_init: false
    scheduled: false

  refs_from_projects:
    on_init: false
    scheduled: false

  metrics:
    on_init: false
    scheduled: false
```

**Comment by strowi** [comment]
Hi @mvisonneau,

thx for clearing this up. I see no logs scheduling anything now.
But the projects are all ignored when using the wildcards option with a log like this:

```
gitlab-ci-exporter_1  | time="2021-01-28T09:50:34Z" level=info msg="ref not configured in the exporter, ignoring pipeline webhook" project-name=sys/runbook ref=master ref-kind=branch
```

BTW shouldn't it be possible to remove the project/wildcard option completely, since the webhook-payload contains those infos? Or is it a security measure to only allow specific gitlab-projects/instances?

**Comment by mvisonneau** [comment]
absolutely, this is currently the behaviour in order to avoid fetching non desired projects or refs. eg: when you configure the hook at the group level but only need a few projects under this group. We could definitely reevaluate it though. For now you will need to have a matching project/wildcard in place.

**Comment by mvisonneau** [comment]
I updated the [examples/webhooks](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/commit/562759d7cd9207b5b8148848968bc101efd9a235) to make it clearer btw 👍

**Comment by strowi** [comment]
Good to know.;)

Shouldn't this disable the pull, but allow the webhook for `sys/*` (at least when using pull the wildcard matches)?

```yaml
server:
  webhook:
    enabled: true
    secret_token: xyz=

gitlab:
  url: https://git.xyz.net

wildcards:
  - owner:
      name: sys
      kind: group
      include_subgroups: true
    pull:
    refs:
      regexp: ".*"
    pipeline:
      jobs:
        enabled: true

pull:
  projects_from_wildcards:
    on_init: false
    scheduled: false

  environments_from_projects:
    on_init: false
    scheduled: false

  refs_from_projects:
    on_init: false
    scheduled: false

  metrics:
    on_init: false
    scheduled: false
```

But as written above, it seems to ignore e.g. 'sys/runbook'..

```
gitlab-ci-exporter_1  | time="2021-01-28T09:50:34Z" level=info msg="ref not configured in the exporter, ignoring pipeline webhook" project-name=sys/runbook ref=master ref-kind=branch

```

**Comment by mvisonneau** [comment]
if believe there is an identation error on your wildcard definition, it should be:

```yaml
wildcards:
  - owner:
      name: sys
      kind: group
      include_subgroups: true
    pull:
      refs:
        regexp: ".*"
      pipeline:
        jobs:
          enabled: true
```

**Comment by mvisonneau** [comment]
I believe I am going to review a bit the attributes hierachy as it also seems a bit confusing 👍

**Comment by strowi** [comment]
Yes there was, but fixing it didin't change the outcome:

```
gitlab-ci-exporter_1  | time="2021-01-28T10:33:43Z" level=info msg="ref not configured in the exporter, ignoring pipeline webhook" project-name=sys/runbook ref=master ref-kind=branch
```
Still trying to figure out the error...

**Comment by strowi** [comment]
Ah, it seems setting `on_init: true` for projects + refs fixes _something_. ;) 
Haven't looked into the code so far, but maybe there is an empty var so nothing to compare to, when using the webhook?

```
pull:
  projects_from_wildcards:
    on_init: true
    scheduled: false

  environments_from_projects:
    on_init: false
    scheduled: false

  refs_from_projects:
    on_init: true
    scheduled: false

  metrics:
    on_init: false
    scheduled: false

```

**Comment by mvisonneau** [comment]
hmm 🤔 which version of the exporter are you using ?

it is strange indeed, actually you shouldn't even need the

```yaml
pull:
  refs:
    regexp: ".*"
```

as the default is `^main|master$`
