### ISSUE TITLE
wildcard search syntax

### ISSUE THREAD

**Issue by Bachib** [mvisonneau/gitlab-ci-pipelines-exporter#218]
What would be the wildcard search syntax ? Could you add it to the doc.

I would like to filter based on which group the project is in.

Ex.: 
- foo/project1
- bar/project2
- test/project3

I want to filter out test and only keep all projects under groups foo and bar.

**Comment by mvisonneau** [comment]
it would be something around those lines:

```yaml
wildcards:
  - owner: { name: foo, kind: group, include_subgroups: true }
  - owner: { name: bar, kind: group, include_subgroups: true }
```

no need to specify the `search` parameter in this case, you can ommit the `include_subgroups: true` if you do not want subgroups.
