### ISSUE TITLE
How to configure to get info of every ref

### ISSUE THREAD

**Issue by gallipi** [mvisonneau/gitlab-ci-pipelines-exporter#230]
HI @mvisonneau,

We've got a project with multiple branches, but we are only getting info of one of them (ref=master). What are we missing in the configuration?

gitlab-ci-pipelines-exporter: **v0.47**
Gitlab CE: **v12.7.5**

config.yml
```
gitlab:
  url: https://gitlab.xxxxxxxx.es
  token: my_token
projects:
  - name: 'aaa/bbb'
```

Log
```
level=info msg="exporter configured" gitlab-endpoint="https://gitlab.xxxx.es" pull-rate-limit=10rps
level=info msg="pull projects from wildcards" on-init=yes scheduled="every 1800s"
level=info msg="pull environments from projects" on-init=yes scheduled="every 1800s"
level=debug msg="reading project" project-name=aaa/bbb
level=debug msg="pull refs from pipelines disabled, not scheduling" project-name=aaa/bbb
level=debug msg="pull environments from project disabled, not scheduling" project-name=aaa/bbb
level=info msg="scheduling projects from wildcards pull" wildcards-count=0
level=info msg="scheduling environments from projects pull" projects-count=1
level=info msg="scheduling refs from projects pull" projects-count=1
level=info msg="scheduling metrics pull" environments-count=0 refs-count=0
level=info msg="http server started" listen-address=":8080" metrics-endpoint-enabled=true openmetrics-encoding-enabled=false pprof-endpoint-enabled=false webhook-endpoint-enabled=false
level=debug msg="pull environments from project disabled, not scheduling" project-name=aaa/bbb
level=info msg="discovered new ref" project-name=aaa/bbb ref=master ref-kind=branch
level=debug msg="reading project" project-name=aaa/bbb
level=debug msg="throttled GitLab requests" for=14.931116ms
level=debug msg="throttled GitLab requests" for=43.368208ms
level=debug msg="listing project pipelines" project-name=aaa/bbb ref=master
level=debug msg="throttled GitLab requests" for=69.414451ms
level=debug msg="throttled GitLab requests" for=68.124278ms
```

Thanks in advanced

**Comment by gallipi** [comment]
found this in issue https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/issues/104#issuecomment-634621417

I've try your example, but still not fetch all branchs

```
wildcards:
  - owner: # Will fetch all the projects of group 'foo'
      name: foo
      kind: group
    refs_regexp: ".*" # Will fetch all the branches/tags/MRs of discovered projects
```

According to documentation I also try this one, but nothing happens

```
wildcards:
    pull:
      refs:
        regexp: ".*"

```

**Comment by mvisonneau** [comment]
@gallipi indeed, the syntax has changed since, sorry about that. I updated the former comment, here is what you need:

```yaml
wildcards:
  - owner: # Will fetch all the projects of group 'foo'
      name: foo
      kind: group
    pull:
      refs:
        regexp: ".*" # Will fetch all the branches/tags/MRs of discovered projects
```
