### ISSUE TITLE
Global setting for output_sparse_status_metrics is not working

### ISSUE THREAD

**Issue by matejzero** [mvisonneau/gitlab-ci-pipelines-exporter#244]
Hello,

I'm using 0.4.8 of the exporter and tried to set global `output_sparse_status_metrics` to true. But it seems like that feature is not working as intended. It only works when set for specific project.

Not working combinations:

```yaml
project_defaults:
  output_sparse_status_metrics: true
projects:
  - name: foo/bar
```

```yaml
project_defaults:
  output_sparse_status_metrics: true
wildcards:
  - owner:
      name: foo
      kind: group
```

```yaml
wildcards:
  - owner:
      name: foo
      kind: group
    output_sparse_status_metrics: true
```

```yaml
defaults:
  output_sparse_status_metrics: true
projects:
  - name: foo/bar
```

It was only working when setting `output_sparse_status_metrics` directly under the project:

```yaml
projects:
  - name: foo/bar
    output_sparse_status_metrics: false
```

Am I understanding the documentation wrong or is this a bug?
