### ISSUE TITLE
Is there a way to get a history of pipelines of the defined ref? 

### ISSUE THREAD

**Issue by vosmax** [mvisonneau/gitlab-ci-pipelines-exporter#247]
Hi @mvisonneau !
**Gitlab version:**
13.9.3
**Grafana version**
7.1.1
**config.yml** 
```
gitlab:
  url: mygitlab.com
  token: SuperSecuredToken
wildcards:
  - owner:
      kind: group
      name: backend
    archived: false
```
I'm willing to find a way how I can get the 20 last pipelines of ref master, for example, to see the dynamic of pipeline duration.   I've played with config values, but no luck.
I do not completely understand what for **Average Pipeline Duration** dashboard if it counts an average of the last pipeline of ref?
