### ISSUE TITLE
Pull all pipeline with all projects and all branches?

### ISSUE THREAD

**Issue by teochenglim** [mvisonneau/gitlab-ci-pipelines-exporter#248]
Is it possible to pull "all project" and "all branch"? Currently it is all project with master branch only.

In the documentation I found the wildcard
https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/main/docs/configuration_syntax.md

```
wildcards:
  - {}

```

**Comment by mvisonneau** [comment]
:wave: hey @teochenglim,

indeed you will need to append the following to your configuration file:

```yaml
project_defaults:
  refs:
    regexp: ".*"
```

the default value is  `^main|master$`

**Comment by teochenglim** [comment]
@mindovermiles262 thank you very much. 
I did a longer version and it works, however it is causing my gitlab system to run the CPU to 100% all the time.
Will try yours tomorrow.

```yaml
# Default settings which can be overridden at the project
# or wildcard level (optional)
project_defaults:
  # Whether to output sparse job and pipeline status metrics.
  # When enabled, only the status label matching the last run
  # of a pipeline or job will be submitted (optional, default: true)
  output_sparse_status_metrics: true

  pull:
    environments:
      # Whether or not to pull project environments & their deployments
      # (optional, default: false)
      enabled: true

      # Filter out by name environments to include
      # (optional, default: ".*")
      name_regexp: ".*"

      # When deployments are based upon tags, you can
      # choose to filter out the ones which you are
      # using to deploy your environment (optional, default: ".*")
      tags_regexp: ".*"

    refs:
      # Filter refs (branches/tags only) to include
      # (optional, default: "^main|master$" -- main or master branch)
      regexp: ".*"

      # If the age of the most recent commit for the ref is greater than
      # this value, the ref won't get exported (optional, default: 0 (disabled))
      # nb: when used in conjuction of pull.from.(pipelines|merge_requests).enabled = true, the creation date
      # of the pipeline is taken in account, not the age of the commit
      max_age_seconds: 0

      from:
        pipelines:
          # Whether to trigger a discovery of the projects refs
          # from the most recent project pipelines when the
          # project is configured/discovered (optional, default: false)
          # This flag is useful if you want/need to obtain pipelines
          # metrics of deleted refs
          enabled: true

          # Maximum number of pipelines to analyze per project
          # to search for refs on init (optional, default: 100)
          depth: 100

        merge_requests:
          # Fetch merge request pipelines refs (optional, default: false)
          enabled: true

          # Maximum number for merge requests pipelines to
          # attempt fetch on each project ref discovery (optional, default: 1)
          depth: 1

    pipeline:
      jobs:
        # Whether to attempt retrieving job level metrics from pipelines.
        # Increases the number of outputed metrics significantly!
        # (optional, default: false)
        enabled: true

        from_child_pipelines:
          # Collect jobs from subsequent child/downstream pipelines
          # (optional, default: true)
          enabled: true

        runner_description:
          # Export the description of the runner which ran the job
          # (optional, default: true)
          enabled: true

          # Whenever the description of a runner will match this regexp
          # The regexp will be used as the value of the runner description instead
          # (optional, default: "shared-runners-manager-(\d*)\.gitlab\.com")
          aggregation_regexp: ".*"

      variables:
        # Fetch pipeline variables in a separate metric (optional, default: false)
        enabled: false

        # Filter pipelines variables to include
        # (optional, default: ".*", all variables)
        regexp: ".*"
```

**Comment by teochenglim** [comment]
@mindovermiles262

What's the different between job and pipeline? They looks the same to me..

**Comment by mvisonneau** [comment]
From this very interesting article: https://about.gitlab.com/blog/2019/07/12/guide-to-ci-cd-pipelines/

**Job**: Instructions that a runner has to execute.
**Pipeline**: A collection of jobs split into different stages.

**Comment by teochenglim** [comment]
I tried the following but it didn't pull all branches

```yaml
project_defaults:
  refs:
    regexp: ".*"

wildcards:
  - {}
```

**Comment by mvisonneau** [comment]
my bad it should be:

```yaml
project_defaults:
  pull:
    refs:
      regexp: ".*"

wildcards:
  - {}
```
