### ISSUE TITLE
Query: Missing ci jobs/pipelines

### ISSUE THREAD

**Issue by bhcopeland** [mvisonneau/gitlab-ci-pipelines-exporter#251]
Hi!

I have my own grafana instance setup, plus tried the`quickstart` docker image. I have a self hosted GitLab instance, and have setup a auth token.

When I run the script, I only get a two projects that show any jobs or pipelines, I seem to have a large amount of data missing (even know its public)

I tried originally with a wildcard, dropped this and defined one of the main projects I want to poll, but I get:

`INFO[2021-04-14T09:56:58Z] scheduling metrics pull                       environments-count=0 refs-count=0INFO[2021-04-14T09:57:28Z] scheduling metrics pull                       environments-count=0 refs-count=0
INFO[2021-04-14T09:57:58Z] scheduling metrics pull                       environments-count=0 refs-count=0`

Am I missing some setting, or something needs to be setup on GitLab?

**Comment by mvisonneau** [comment]
👋 hey @bhcopeland, could you please share a sanitized version of your configuration file?

**Comment by zatricky** [comment]
It may be helpful to add (to the readme) recommendations/best practices on how to set up the token. For example which impersonation scopes are required, or that user tokens will have access only to public projects and their own projects, or that a dedicated user could be created that you'd need to add to all groups as a "Reporter".

**Comment by bhcopeland** [comment]
Thanks guys. So the user I have setup it myself. I am a admin on a dedicated GitLab intance, and am a owner to all projects, which is higher than Reporter, so this should be okay, right?

`gitlab:  
     url: https://git.xxxxt.org  
     token: xxxxx

owner:   
   name: foobargroup
   kind: group
   pull:
    refs:
     regexp: ".*" # Will fetch all the branches/tags/MRs of discovered projects`

**Comment by rj175** [comment]
@bhcopeland I was looking to include all branches within a project and I found that my following config did as I needed:
```
---
gitlab:
  url: <URL>
  token: <TOKEN>
wildcards:
  - owner:
      name: <OWNER NAME>
      kind: group
      include_subgroups: true
    pull:
      environments:
        regexp: "^*$"
 ```
Hope this helps.

**Comment by kha7iq** [comment]
If using wildcard `{}` following config in helm chart works well.
```yaml
config:
  project_defaults:
    output_sparse_status_metrics: true
    pull:
      environments:
        enabled: false
        regexp: ".*"
        exclude_stopped: true
      refs:
        branches:
          enabled: true
          regexp: "^main|master|dev$"
          most_recent: 0
          max_age_seconds: 0
          exclude_deleted: true
        tags:
          enabled: true
          regexp: ".*"
          most_recent: 0
          max_age_seconds: 0
          exclude_deleted: true
        merge_requests:
          enabled: false
          most_recent: 0
          max_age_seconds: 0
      pipeline:
        jobs:
          enabled: true
          from_child_pipelines:
            enabled: false
          runner_description:
            enabled: true
            aggregation_regexp: shared-runners-manager-(\d*)\.gitlab\.com
        variables:
          enabled: false
          regexp: ".*"
  gitlab:
    url: https://gitlab.example.com
  wildcards:
  - {}
```
