### ISSUE TITLE
how to fetch only branches and not tags

### ISSUE THREAD

**Issue by bazron** [mvisonneau/gitlab-ci-pipelines-exporter#254]
How can I fetch only branches and not tags? I don't need any metrics with the tag `{kind="branch"}`

**Comment by mvisonneau** [comment]
Hey @bazron, it is unfortunately not possible to completely disable whether `tag` or `branch` fetching.

The only option you have is to use a regexp to filter them out for the moment.

I believe this should be a fairly straightforward feature to add though.

**Comment by mvisonneau** [comment]
:wave: @bazron, I implemented this feature as part of [v0.5.0](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/tag/v0.5.0)!

You can now set the following to exclude branches:

```yaml
project_defaults:
  pull:
    refs:
      branches:
        enabled: false
```
