### ISSUE TITLE
Get metrics for all branches and merge-requests from specified project

### ISSUE THREAD

**Issue by Dexig** [mvisonneau/gitlab-ci-pipelines-exporter#256]
Hello!. Thx u for the awesome exporter.

I try to configure exporter with only using webhooks.
I want to get metrics about pipelines and jobs from one specified project for the all branches/tags and merge-requests.
But exporter didn't show merge-requests metrics in  `/metrics` endpoint. There is only tags and branches.
Why?(((

My configuration:

```yaml
server:
  webhook:
    enabled: true
    secret_token: xxx
  listen_address: >-
    0.0.0.0:9211
pull:
  projects_from_wildcards:
    on_init: false
    scheduled: false
  environments_from_projects:
    on_init: false
    scheduled: false
  refs_from_projects:
    on_init: false
    scheduled: false
  metrics:
    on_init: false
    scheduled: false
gitlab:
  url: "https://gl.xxxx.ru"
  token: "xxxx"
project_defaults:
  output_sparse_status_metrics: false
projects:
  - name: some-group/some-project
    pull:
      pipeline:
        jobs:
          enabled: true
          from_child_pipelines:
            enabled: true
      refs:
        from:
          merge_requests:
            depth: 1
            enabled: true
          pipelines:
            depth: 100
            enabled: true
        max_age_seconds: 5184000
        regexp: .*

```

what is wrong?

There are similar entries in the logs:
```
апр 19 20:38:34 some-host docker[1343]: time="2021-04-19T17:38:34Z" level=info msg="received a pipeline webhook from GitLab for a ref, triggering metrics pull" project-name=some-group/some-project ref=XXX-123 ref-kind=merge-request
```

Thanks!
