### ISSUE TITLE
Problem getting values ​​for gitlab_ci_pipeline_job

### ISSUE THREAD

**Issue by yehudimikhael** [mvisonneau/gitlab-ci-pipelines-exporter#258]
I am checking that queries related to the $status **$gitlab_ci_pipeline_environment_deployment_status**
and **$gitlab_ci_pipeline_pipeline_status** I can get.

However, the information about **$gitlab_ci_pipeline_job_status** I cannot bring and there is no error in the logs.

I'm using the version https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/download/v0.4.8/gitlab-ci-pipelines-exporter_v0.4.8_linux_amd64.tar.gz

**Comment by yehudimikhael** [comment]
![image](https://user-images.githubusercontent.com/8180127/116268262-888d0700-a753-11eb-818c-16008695613b.png)

**Comment by yehudimikhael** [comment]
I found that with the version mvisonneau / gitlab-ci-pipelines-exporter: 0.4.2 I was able to obtain the values ​​referring to $gitlab_ci_pipeline_job

**Comment by mvisonneau** [comment]
:wave: hey @yehudimikhael, could you share a sanitized version of your config file?

**Comment by yehudimikhael** [comment]
`server:
  # [address:port] to make the process listen
  # upon (optional, default: :8080)
  listen_address: :8888

  # Enable profiling pages
  # at /debug/pprof (optional, default: false)
  enable_pprof: false

  metrics:
    # Enable /metrics endpoint (optional, default: true)
    enabled: true

    # Enable OpenMetrics content encoding in
    # prometheus HTTP handler (optional, default: false)
    # see: https://godoc.org/github.com/prometheus/client_golang/prometheus/promhttp#HandlerOpts
    enable_openmetrics_encoding: true
# URL and Token with sufficient permissions to access
# your GitLab's projects pipelines informations (optional)
gitlab:
  # URL of your GitLab instance (optional, default: https://gitlab.com)
  url: https://gitlab.xpto.com

  # Alternative URL for determining health of
  # GitLab API for the readiness probe (optional, default: https://gitlab.com)
  # it can also be defined using the --gitlab-health-url flag or $GCPE_GITLAB_HEALTH_URL
  # environment variable
  health_url: https://gitlab.xpto.com/-/health

  # Enable verification of readiness for target
  # GitLab instance calling `health_url` (optional, default: true)
  enable_health_check: true

  # Enable TLS validation for target
  # GitLab instance (handy when self-hosting) (optional, default: true)
  enable_tls_verify: true

pull:
  # Global rate limit for the GitLab API request/sec
  # (optional, default: 10)
  maximum_gitlab_api_requests_per_second: 10

  projects_from_wildcards:
    # Whether to trigger a discovery or not when the
    # exporter starts (optional, default: true)
    on_init: true

    # Whether to attempt retrieving new projects from wildcards
    # on a regular basis (optional, default: true)
    scheduled: true

    # Interval in seconds to discover projects
    # from wildcards (optional, default: 1800)
    interval_seconds: 1800

  environments_from_projects:
    # Whether to trigger a discovery of project environments when
    # exporter starts (optional, default: true)
    on_init: true

    # Whether to attempt retrieving project environments
    # on a regular basis (optional, default: true)
    scheduled: true

    # Interval in seconds to discover project environments
    # (optional, default: 300)
    interval_seconds: 300

  refs_from_projects:
    # Whether to trigger a discovery of project refs from
    # branches, tags and merge requests when the
    # exporter starts (optional, default: true)
    # nb: merge requests refs discovery needs to be
    # additionally enabled on a per project basis
    on_init: true

    # Whether to attempt retrieving project refs from branches,
    # tags & merge requests on a regular basis (optional, default: true)
    scheduled: true

    # Interval in seconds to discover refs
    # from projects branches and tags (optional, default: 300)
    interval_seconds: 300

  metrics:
    # Whether or not to trigger a pull of the metrics when the
    # exporter starts (optional, default: true)
    on_init: true

    # Whether or not to attempt refreshing the metrics
    # on a regular basis (optional, default: true)
    scheduled: true

    # Interval in seconds to pull metrics from
    # discovered project refs (optional, default: 30)
    interval_seconds: 30

garbage_collect:
  projects:
    # Whether or not to trigger a garbage collection of the
    # projects when the exporter starts (optional, default: false)
    on_init: false

    # Whether or not to attempt garbage collecting the projects
    # on a regular basis (optional, default: true)
    scheduled: true

    # Interval in seconds to garbage collect projects
    # (optional, default: 14400)
    interval_seconds: 14400

  environments:
    # Whether or not to trigger a garbage collection of the
    # environments when the exporter starts (optional, default: false)
    on_init: false

    # Whether or not to attempt garbage collecting the environments
    # on a regular basis (optional, default: true)
    scheduled: true

    # Interval in seconds to garbage collect environments
    # (optional, default: 14400)
    interval_seconds: 14400

  refs:
    # Whether or not to trigger a garbage collection of the
    # projects refs when the exporter starts (optional, default: false)
    on_init: false

    # Whether or not to attempt garbage collecting the projects refs
    # on a regular basis (optional, default: true)
    scheduled: true

    # Interval in seconds to garbage collect projects refs
    # from projects branches and tags (optional, default: 1800)
    interval_seconds: 1800

  metrics:
    # Whether or not to trigger a garbage collection of the
    # metrics when the exporter starts (optional, default: false)
    on_init: false

    # Whether or not to attempt garbage collecting the metrics
    # on a regular basis (optional, default: true)
    scheduled: true

    # Interval in seconds to garbage collect metrics
    # (optional, default: 300)
    interval_seconds: 300

# Default settings which can be overridden at the project
# or wildcard level (optional)
project_defaults:
  # Whether to output sparse job and pipeline status metrics.
  # When enabled, only the status label matching the last run
  # of a pipeline or job will be submitted (optional, default: true)
  output_sparse_status_metrics: true

  pull:
    environments:
      # Whether or not to pull project environments & their deployments
      # (optional, default: false)
      enabled: false

      # Filter out by name environments to include
      # (optional, default: ".*")
      name_regexp: ".*"

      # When deployments are based upon tags, you can
      # choose to filter out the ones which you are
      # using to deploy your environment (optional, default: ".*")
      tags_regexp: ".*"

    refs:
      # Filter refs (branches/tags only) to include
      # (optional, default: "^main|master$" -- main or master branch)
      regexp: ".*"

      # If the age of the most recent commit for the ref is greater than
      # this value, the ref won't get exported (optional, default: 0 (disabled))
      # nb: when used in conjuction of pull.from.(pipelines|merge_requests).enabled = true, the creation date
      # of the pipeline is taken in account, not the age of the commit
      max_age_seconds: 0

      from:
        pipelines:
          # Whether to trigger a discovery of the projects refs
          # from the most recent project pipelines when the
          # project is configured/discovered (optional, default: false)
          # This flag is useful if you want/need to obtain pipelines
          # metrics of deleted refs
          enabled: false

          # Maximum number of pipelines to analyze per project
          # to search for refs on init (optional, default: 100)
          depth: 100

        merge_requests:
          # Fetch merge request pipelines refs (optional, default: false)
          enabled: false

          # Maximum number for merge requests pipelines to
          # attempt fetch on each project ref discovery (optional, default: 1)
          depth: 1

    pipeline:
      jobs:
        # Whether to attempt retrieving job level metrics from pipelines.
        # Increases the number of outputed metrics significantly!
        # (optional, default: false)
        enabled: false

        from_child_pipelines:
          # Collect jobs from subsequent child/downstream pipelines
          # (optional, default: true)
          enabled: true

        runner_description:
          # Export the description of the runner which ran the job
          # (optional, default: true)
          enabled: true

          # Whenever the description of a runner will match this regexp
          # The regexp will be used as the value of the runner description instead
          # (optional, default: "shared-runners-manager-(\d*)\.gitlab\.com")
          aggregation_regexp: shared-runners-manager-(\d*)\.gitlab\.xpto\.com

      variables:
        # Fetch pipeline variables in a separate metric (optional, default: false)
        enabled: false

        # Filter pipelines variables to include
        # (optional, default: ".*", all variables)
        regexp: ".*"

# Dynamically fetch projects to monitor using a wildcard (optional)
wildcards:
  - # Define the owner of the projects we want to look for (optional)
    owner:
      # Name of the owner (required)
      name: sales

      # Owner kind: can be either 'group' or 'user' (required)
      kind: group

      # if owner kind is 'group', whether to include subgroups
      # or not (optional, default: false)
      include_subgroups: true

    # Search expression to filter out projects
    # (optional, default: '' -- no filter/all projects)
    search: ""

    # Including archived projects or not
    # (optional, default: false)
    archived: false

    # Here are all the project parameters which can be overriden (optional)
    pull:
      environments:
        # Whether or not to pull project environments & their deployments
        # (optional, default: false)
        enabled: true

        # Filter out by name environments to include
        # (optional, default: ".*")
        name_regexp: ".*"

        # When deployments are based upon tags, you can
        # choose to filter out the ones which you are
        # using to deploy your environment (optional, default: ".*")
        tags_regexp: ".*"

      refs:
        # Filter refs (branches/tags only) to include
        # (optional, default: "^main|master$" -- main or master branch)
        regexp: "^.*"

        # If the age of the most recent commit for the ref is greater than
        # this value, the ref won't get exported (optional, default: 0 (disabled))
        # nb: when used in conjuction of pull.from.(pipelines|merge_requests).enabled = true, the creation date
        # of the pipeline is taken in account, not the age of the commit
        max_age_seconds: 0

        from:
          pipelines:
            # Whether to trigger a discovery of the projects refs
            # from the most recent project pipelines when the
            # project is configured/discovered (optional, default: false)
            # This flag is useful if you want/need to obtain pipelines
            # metrics of deleted refs
            enabled: false

            # Maximum number of pipelines to analyze per project
            # to search for refs on init (optional, default: 100, min: 1, max: 100)
            depth: 100

          merge_requests:
            # Fetch merge request pipelines refs (optional, default: false)
            enabled: true

            # Maximum number for merge requests pipelines to
            # attempt fetch on each project ref discovery (optional, default: 1)
            depth: 1

      pipeline:
        jobs:
          # Whether to attempt retrieving job level metrics from pipelines.
          # Increases the number of outputed metrics significantly!
          # (optional, default: false)
          enabled: true

          from_child_pipelines:
            # Collect jobs from subsequent child/downstream pipelines
            # (optional, default: true)
            enabled: true

          runner_description:
            # Export the description of the runner which ran the job
            # (optional, default: true)
            enabled: true

            # Whenever the description of a runner will match this regexp
            # The regexp will be used as the value of the runner description instead
            # (optional, default: "shared-runners-manager-(\d*)\.gitlab\.com")
            aggregation_regexp: shared-runners-manager-(\d*)\.gitlab\.xpto\.com

        variables:
          # Fetch pipeline variables in a separate metric (optional, default: false)
          enabled: false

          # Filter pipelines variables to include
          # (optional, default: ".*", all variables)
          regexp: ".*"
`

**Comment by yehudimikhael** [comment]
server:
  # [address:port] to make the process listen
  # upon (optional, default: :8080)
  listen_address: :8888

  # Enable profiling pages
  # at /debug/pprof (optional, default: false)
  enable_pprof: false

  metrics:
    # Enable /metrics endpoint (optional, default: true)
    enabled: true

    # Enable OpenMetrics content encoding in
    # prometheus HTTP handler (optional, default: false)
    # see: https://godoc.org/github.com/prometheus/client_golang/prometheus/promhttp#HandlerOpts
    enable_openmetrics_encoding: true
# URL and Token with sufficient permissions to access
# your GitLab's projects pipelines informations (optional)
gitlab:
  # URL of your GitLab instance (optional, default: https://gitlab.com)
  url: https://gitlab.xpto.com

  # Alternative URL for determining health of
  # GitLab API for the readiness probe (optional, default: https://gitlab.com)
  # it can also be defined using the --gitlab-health-url flag or $GCPE_GITLAB_HEALTH_URL
  # environment variable
  health_url: https://gitlab.xpto.com/-/health

  # Enable verification of readiness for target
  # GitLab instance calling `health_url` (optional, default: true)
  enable_health_check: true

  # Enable TLS validation for target
  # GitLab instance (handy when self-hosting) (optional, default: true)
  enable_tls_verify: true

pull:
  # Global rate limit for the GitLab API request/sec
  # (optional, default: 10)
  maximum_gitlab_api_requests_per_second: 10

  projects_from_wildcards:
    # Whether to trigger a discovery or not when the
    # exporter starts (optional, default: true)
    on_init: true

    # Whether to attempt retrieving new projects from wildcards
    # on a regular basis (optional, default: true)
    scheduled: true

    # Interval in seconds to discover projects
    # from wildcards (optional, default: 1800)
    interval_seconds: 1800

  environments_from_projects:
    # Whether to trigger a discovery of project environments when
    # exporter starts (optional, default: true)
    on_init: true

    # Whether to attempt retrieving project environments
    # on a regular basis (optional, default: true)
    scheduled: true

    # Interval in seconds to discover project environments
    # (optional, default: 300)
    interval_seconds: 300

  refs_from_projects:
    # Whether to trigger a discovery of project refs from
    # branches, tags and merge requests when the
    # exporter starts (optional, default: true)
    # nb: merge requests refs discovery needs to be
    # additionally enabled on a per project basis
    on_init: true

    # Whether to attempt retrieving project refs from branches,
    # tags & merge requests on a regular basis (optional, default: true)
    scheduled: true

    # Interval in seconds to discover refs
    # from projects branches and tags (optional, default: 300)
    interval_seconds: 300

  metrics:
    # Whether or not to trigger a pull of the metrics when the
    # exporter starts (optional, default: true)
    on_init: true

    # Whether or not to attempt refreshing the metrics
    # on a regular basis (optional, default: true)
    scheduled: true

    # Interval in seconds to pull metrics from
    # discovered project refs (optional, default: 30)
    interval_seconds: 30

garbage_collect:
  projects:
    # Whether or not to trigger a garbage collection of the
    # projects when the exporter starts (optional, default: false)
    on_init: false

    # Whether or not to attempt garbage collecting the projects
    # on a regular basis (optional, default: true)
    scheduled: true

    # Interval in seconds to garbage collect projects
    # (optional, default: 14400)
    interval_seconds: 14400

  environments:
    # Whether or not to trigger a garbage collection of the
    # environments when the exporter starts (optional, default: false)
    on_init: false

    # Whether or not to attempt garbage collecting the environments
    # on a regular basis (optional, default: true)
    scheduled: true

    # Interval in seconds to garbage collect environments
    # (optional, default: 14400)
    interval_seconds: 14400

  refs:
    # Whether or not to trigger a garbage collection of the
    # projects refs when the exporter starts (optional, default: false)
    on_init: false

    # Whether or not to attempt garbage collecting the projects refs
    # on a regular basis (optional, default: true)
    scheduled: true

    # Interval in seconds to garbage collect projects refs
    # from projects branches and tags (optional, default: 1800)
    interval_seconds: 1800

  metrics:
    # Whether or not to trigger a garbage collection of the
    # metrics when the exporter starts (optional, default: false)
    on_init: false

    # Whether or not to attempt garbage collecting the metrics
    # on a regular basis (optional, default: true)
    scheduled: true

    # Interval in seconds to garbage collect metrics
    # (optional, default: 300)
    interval_seconds: 300

# Default settings which can be overridden at the project
# or wildcard level (optional)
project_defaults:
  # Whether to output sparse job and pipeline status metrics.
  # When enabled, only the status label matching the last run
  # of a pipeline or job will be submitted (optional, default: true)
  output_sparse_status_metrics: true

  pull:
    environments:
      # Whether or not to pull project environments & their deployments
      # (optional, default: false)
      enabled: false

      # Filter out by name environments to include
      # (optional, default: ".*")
      name_regexp: ".*"

      # When deployments are based upon tags, you can
      # choose to filter out the ones which you are
      # using to deploy your environment (optional, default: ".*")
      tags_regexp: ".*"

    refs:
      # Filter refs (branches/tags only) to include
      # (optional, default: "^main|master$" -- main or master branch)
      regexp: ".*"

      # If the age of the most recent commit for the ref is greater than
      # this value, the ref won't get exported (optional, default: 0 (disabled))
      # nb: when used in conjuction of pull.from.(pipelines|merge_requests).enabled = true, the creation date
      # of the pipeline is taken in account, not the age of the commit
      max_age_seconds: 0

      from:
        pipelines:
          # Whether to trigger a discovery of the projects refs
          # from the most recent project pipelines when the
          # project is configured/discovered (optional, default: false)
          # This flag is useful if you want/need to obtain pipelines
          # metrics of deleted refs
          enabled: false

          # Maximum number of pipelines to analyze per project
          # to search for refs on init (optional, default: 100)
          depth: 100

        merge_requests:
          # Fetch merge request pipelines refs (optional, default: false)
          enabled: false

          # Maximum number for merge requests pipelines to
          # attempt fetch on each project ref discovery (optional, default: 1)
          depth: 1

    pipeline:
      jobs:
        # Whether to attempt retrieving job level metrics from pipelines.
        # Increases the number of outputed metrics significantly!
        # (optional, default: false)
        enabled: false

        from_child_pipelines:
          # Collect jobs from subsequent child/downstream pipelines
          # (optional, default: true)
          enabled: true

        runner_description:
          # Export the description of the runner which ran the job
          # (optional, default: true)
          enabled: true

          # Whenever the description of a runner will match this regexp
          # The regexp will be used as the value of the runner description instead
          # (optional, default: "shared-runners-manager-(\d*)\.gitlab\.com")
          aggregation_regexp: shared-runners-manager-(\d*)\.gitlab\.xpto\.com

      variables:
        # Fetch pipeline variables in a separate metric (optional, default: false)
        enabled: false

        # Filter pipelines variables to include
        # (optional, default: ".*", all variables)
        regexp: ".*"

# Dynamically fetch projects to monitor using a wildcard (optional)
wildcards:
  - # Define the owner of the projects we want to look for (optional)
    owner:
      # Name of the owner (required)
      name: sales

      # Owner kind: can be either 'group' or 'user' (required)
      kind: group

      # if owner kind is 'group', whether to include subgroups
      # or not (optional, default: false)
      include_subgroups: true

    # Search expression to filter out projects
    # (optional, default: '' -- no filter/all projects)
    search: ""

    # Including archived projects or not
    # (optional, default: false)
    archived: false

    # Here are all the project parameters which can be overriden (optional)
    pull:
      environments:
        # Whether or not to pull project environments & their deployments
        # (optional, default: false)
        enabled: true

        # Filter out by name environments to include
        # (optional, default: ".*")
        name_regexp: ".*"

        # When deployments are based upon tags, you can
        # choose to filter out the ones which you are
        # using to deploy your environment (optional, default: ".*")
        tags_regexp: ".*"

      refs:
        # Filter refs (branches/tags only) to include
        # (optional, default: "^main|master$" -- main or master branch)
        regexp: "^.*"

        # If the age of the most recent commit for the ref is greater than
        # this value, the ref won't get exported (optional, default: 0 (disabled))
        # nb: when used in conjuction of pull.from.(pipelines|merge_requests).enabled = true, the creation date
        # of the pipeline is taken in account, not the age of the commit
        max_age_seconds: 0

        from:
          pipelines:
            # Whether to trigger a discovery of the projects refs
            # from the most recent project pipelines when the
            # project is configured/discovered (optional, default: false)
            # This flag is useful if you want/need to obtain pipelines
            # metrics of deleted refs
            enabled: false

            # Maximum number of pipelines to analyze per project
            # to search for refs on init (optional, default: 100, min: 1, max: 100)
            depth: 100

          merge_requests:
            # Fetch merge request pipelines refs (optional, default: false)
            enabled: true

            # Maximum number for merge requests pipelines to
            # attempt fetch on each project ref discovery (optional, default: 1)
            depth: 1

      pipeline:
        jobs:
          # Whether to attempt retrieving job level metrics from pipelines.
          # Increases the number of outputed metrics significantly!
          # (optional, default: false)
          enabled: true

          from_child_pipelines:
            # Collect jobs from subsequent child/downstream pipelines
            # (optional, default: true)
            enabled: true

          runner_description:
            # Export the description of the runner which ran the job
            # (optional, default: true)
            enabled: true

            # Whenever the description of a runner will match this regexp
            # The regexp will be used as the value of the runner description instead
            # (optional, default: "shared-runners-manager-(\d*)\.gitlab\.com")
            aggregation_regexp: shared-runners-manager-(\d*)\.gitlab\.xpto\.com

        variables:
          # Fetch pipeline variables in a separate metric (optional, default: false)
          enabled: false

          # Filter pipelines variables to include
          # (optional, default: ".*", all variables)
          regexp: ".*"

**Comment by yehudimikhael** [comment]
```yml

server:
  # [address:port] to make the process listen
  # upon (optional, default: :8080)
  listen_address: :8888

  # Enable profiling pages
  # at /debug/pprof (optional, default: false)
  enable_pprof: false

  metrics:
    # Enable /metrics endpoint (optional, default: true)
    enabled: true

    # Enable OpenMetrics content encoding in
    # prometheus HTTP handler (optional, default: false)
    # see: https://godoc.org/github.com/prometheus/client_golang/prometheus/promhttp#HandlerOpts
    enable_openmetrics_encoding: true
# URL and Token with sufficient permissions to access
# your GitLab's projects pipelines informations (optional)
gitlab:
  # URL of your GitLab instance (optional, default: https://gitlab.com)
  url: https://gitlab.xpto.com

  # Alternative URL for determining health of
  # GitLab API for the readiness probe (optional, default: https://gitlab.com)
  # it can also be defined using the --gitlab-health-url flag or $GCPE_GITLAB_HEALTH_URL
  # environment variable
  health_url: https://gitlab.xpto.com/-/health

  # Enable verification of readiness for target
  # GitLab instance calling `health_url` (optional, default: true)
  enable_health_check: true

  # Enable TLS validation for target
  # GitLab instance (handy when self-hosting) (optional, default: true)
  enable_tls_verify: true

pull:
  # Global rate limit for the GitLab API request/sec
  # (optional, default: 10)
  maximum_gitlab_api_requests_per_second: 10

  projects_from_wildcards:
    # Whether to trigger a discovery or not when the
    # exporter starts (optional, default: true)
    on_init: true

    # Whether to attempt retrieving new projects from wildcards
    # on a regular basis (optional, default: true)
    scheduled: true

    # Interval in seconds to discover projects
    # from wildcards (optional, default: 1800)
    interval_seconds: 1800

  environments_from_projects:
    # Whether to trigger a discovery of project environments when
    # exporter starts (optional, default: true)
    on_init: true

    # Whether to attempt retrieving project environments
    # on a regular basis (optional, default: true)
    scheduled: true

    # Interval in seconds to discover project environments
    # (optional, default: 300)
    interval_seconds: 300

  refs_from_projects:
    # Whether to trigger a discovery of project refs from
    # branches, tags and merge requests when the
    # exporter starts (optional, default: true)
    # nb: merge requests refs discovery needs to be
    # additionally enabled on a per project basis
    on_init: true

    # Whether to attempt retrieving project refs from branches,
    # tags & merge requests on a regular basis (optional, default: true)
    scheduled: true

    # Interval in seconds to discover refs
    # from projects branches and tags (optional, default: 300)
    interval_seconds: 300

  metrics:
    # Whether or not to trigger a pull of the metrics when the
    # exporter starts (optional, default: true)
    on_init: true

    # Whether or not to attempt refreshing the metrics
    # on a regular basis (optional, default: true)
    scheduled: true

    # Interval in seconds to pull metrics from
    # discovered project refs (optional, default: 30)
    interval_seconds: 30

garbage_collect:
  projects:
    # Whether or not to trigger a garbage collection of the
    # projects when the exporter starts (optional, default: false)
    on_init: false

    # Whether or not to attempt garbage collecting the projects
    # on a regular basis (optional, default: true)
    scheduled: true

    # Interval in seconds to garbage collect projects
    # (optional, default: 14400)
    interval_seconds: 14400

  environments:
    # Whether or not to trigger a garbage collection of the
    # environments when the exporter starts (optional, default: false)
    on_init: false

    # Whether or not to attempt garbage collecting the environments
    # on a regular basis (optional, default: true)
    scheduled: true

    # Interval in seconds to garbage collect environments
    # (optional, default: 14400)
    interval_seconds: 14400

  refs:
    # Whether or not to trigger a garbage collection of the
    # projects refs when the exporter starts (optional, default: false)
    on_init: false

    # Whether or not to attempt garbage collecting the projects refs
    # on a regular basis (optional, default: true)
    scheduled: true

    # Interval in seconds to garbage collect projects refs
    # from projects branches and tags (optional, default: 1800)
    interval_seconds: 1800

  metrics:
    # Whether or not to trigger a garbage collection of the
    # metrics when the exporter starts (optional, default: false)
    on_init: false

    # Whether or not to attempt garbage collecting the metrics
    # on a regular basis (optional, default: true)
    scheduled: true

    # Interval in seconds to garbage collect metrics
    # (optional, default: 300)
    interval_seconds: 300

# Default settings which can be overridden at the project
# or wildcard level (optional)
project_defaults:
  # Whether to output sparse job and pipeline status metrics.
  # When enabled, only the status label matching the last run
  # of a pipeline or job will be submitted (optional, default: true)
  output_sparse_status_metrics: true

  pull:
    environments:
      # Whether or not to pull project environments & their deployments
      # (optional, default: false)
      enabled: false

      # Filter out by name environments to include
      # (optional, default: ".*")
      name_regexp: ".*"

      # When deployments are based upon tags, you can
      # choose to filter out the ones which you are
      # using to deploy your environment (optional, default: ".*")
      tags_regexp: ".*"

    refs:
      # Filter refs (branches/tags only) to include
      # (optional, default: "^main|master$" -- main or master branch)
      regexp: ".*"

      # If the age of the most recent commit for the ref is greater than
      # this value, the ref won't get exported (optional, default: 0 (disabled))
      # nb: when used in conjuction of pull.from.(pipelines|merge_requests).enabled = true, the creation date
      # of the pipeline is taken in account, not the age of the commit
      max_age_seconds: 0

      from:
        pipelines:
          # Whether to trigger a discovery of the projects refs
          # from the most recent project pipelines when the
          # project is configured/discovered (optional, default: false)
          # This flag is useful if you want/need to obtain pipelines
          # metrics of deleted refs
          enabled: false

          # Maximum number of pipelines to analyze per project
          # to search for refs on init (optional, default: 100)
          depth: 100

        merge_requests:
          # Fetch merge request pipelines refs (optional, default: false)
          enabled: false

          # Maximum number for merge requests pipelines to
          # attempt fetch on each project ref discovery (optional, default: 1)
          depth: 1

    pipeline:
      jobs:
        # Whether to attempt retrieving job level metrics from pipelines.
        # Increases the number of outputed metrics significantly!
        # (optional, default: false)
        enabled: false

        from_child_pipelines:
          # Collect jobs from subsequent child/downstream pipelines
          # (optional, default: true)
          enabled: true

        runner_description:
          # Export the description of the runner which ran the job
          # (optional, default: true)
          enabled: true

          # Whenever the description of a runner will match this regexp
          # The regexp will be used as the value of the runner description instead
          # (optional, default: "shared-runners-manager-(\d*)\.gitlab\.com")
          aggregation_regexp: shared-runners-manager-(\d*)\.gitlab\.xpto\.com

      variables:
        # Fetch pipeline variables in a separate metric (optional, default: false)
        enabled: false

        # Filter pipelines variables to include
        # (optional, default: ".*", all variables)
        regexp: ".*"

# Dynamically fetch projects to monitor using a wildcard (optional)
wildcards:
  - # Define the owner of the projects we want to look for (optional)
    owner:
      # Name of the owner (required)
      name: sales

      # Owner kind: can be either 'group' or 'user' (required)
      kind: group

      # if owner kind is 'group', whether to include subgroups
      # or not (optional, default: false)
      include_subgroups: true

    # Search expression to filter out projects
    # (optional, default: '' -- no filter/all projects)
    search: ""

    # Including archived projects or not
    # (optional, default: false)
    archived: false

    # Here are all the project parameters which can be overriden (optional)
    pull:
      environments:
        # Whether or not to pull project environments & their deployments
        # (optional, default: false)
        enabled: true

        # Filter out by name environments to include
        # (optional, default: ".*")
        name_regexp: ".*"

        # When deployments are based upon tags, you can
        # choose to filter out the ones which you are
        # using to deploy your environment (optional, default: ".*")
        tags_regexp: ".*"

      refs:
        # Filter refs (branches/tags only) to include
        # (optional, default: "^main|master$" -- main or master branch)
        regexp: "^.*"

        # If the age of the most recent commit for the ref is greater than
        # this value, the ref won't get exported (optional, default: 0 (disabled))
        # nb: when used in conjuction of pull.from.(pipelines|merge_requests).enabled = true, the creation date
        # of the pipeline is taken in account, not the age of the commit
        max_age_seconds: 0

        from:
          pipelines:
            # Whether to trigger a discovery of the projects refs
            # from the most recent project pipelines when the
            # project is configured/discovered (optional, default: false)
            # This flag is useful if you want/need to obtain pipelines
            # metrics of deleted refs
            enabled: false

            # Maximum number of pipelines to analyze per project
            # to search for refs on init (optional, default: 100, min: 1, max: 100)
            depth: 100

          merge_requests:
            # Fetch merge request pipelines refs (optional, default: false)
            enabled: true

            # Maximum number for merge requests pipelines to
            # attempt fetch on each project ref discovery (optional, default: 1)
            depth: 1

      pipeline:
        jobs:
          # Whether to attempt retrieving job level metrics from pipelines.
          # Increases the number of outputed metrics significantly!
          # (optional, default: false)
          enabled: true

          from_child_pipelines:
            # Collect jobs from subsequent child/downstream pipelines
            # (optional, default: true)
            enabled: true

          runner_description:
            # Export the description of the runner which ran the job
            # (optional, default: true)
            enabled: true

            # Whenever the description of a runner will match this regexp
            # The regexp will be used as the value of the runner description instead
            # (optional, default: "shared-runners-manager-(\d*)\.gitlab\.com")
            aggregation_regexp: shared-runners-manager-(\d*)\.gitlab\.xpto\.com

        variables:
          # Fetch pipeline variables in a separate metric (optional, default: false)
          enabled: false

          # Filter pipelines variables to include
          # (optional, default: ".*", all variables)
          regexp: ".*"


```

**Comment by yehudimikhael** [comment]
![image](https://user-images.githubusercontent.com/8180127/116592825-d0985f00-a8f6-11eb-95a0-3305e3c6f81c.png)

**Comment by mvisonneau** [comment]
@yehudimikhael, in your last screenshot I can see the `gitlab_ci_pipeline_job_status` metric being reported. Isn't it what you were looking for? :thinking:

**Comment by OPSTime** [comment]
Me too.
After testing, I found that some job related metrics disappeared, starting with version 0.4.4.

**Comment by mvisonneau** [comment]
@OPSTime, can you please share a sanitized version of your config? I am still unsure about what this issue is about.

**Comment by OPSTime** [comment]
**config:**
```
# Log configuration
log:
  # Set the logging level
  # allowed values: trace, debug, info, warning, error, fatal or panic
  # (optional, default: info)
  level: debug

  format: text

server:
  # [address:port] to make the process listen
  # upon (optional, default: :8080)
  listen_address: :8080
  
  # Enable profiling pages
  enable_pprof: false
  
  metrics:
    # Enable /metrics endpoint (optional, default: true)
    enabled: true

gitlab:
  url: https://gitlab.example.com
  token: xxxxxx

# Pull jobs related metrics on all projects
project_defaults:
  pull:
    pipeline:
      jobs:
        enabled: true

# Example public projects to monitor
projects:
  - name: front-end/project_name
    pull:
      environments:
        enabled: true
      refs:
        regexp: "^stage?|/^features?/|^bug?|^hotfix?|^master$"
```

**Comment by OPSTime** [comment]
Hi, @mvisonneau  ,did you find out what caused the problem?

**Comment by OPSTime** [comment]
@mvisonneau ？

**Comment by cPanelRicky** [comment]
@mvisonneau, I too am seeing job metrics not being populated. I am also not able to get child pipelines to be followed either despite having it explicitly declared in the config.

Config
```yaml
server:
  listen_address: :8080
  webhook:
    enabled: true
    secret_token: $uper$ecr3t
gitlab:
  url: https://gitlab-url/
  token: $uper$ecr3t
  health_url: https://gitlab-url/-/health
projects:
  - name: awesome/product
    pipeline:
      jobs:
        enabled: true
        from_child_pipelines:
          enabled: true
      variables:
        enabled: true
```

Below are the resulting metrics
```
$ curl -sL https://gcpe.domain.tld/metrics | grep -v '^#' | grep gitlab_ci_ | awk -F'{' '{print $1}'
gitlab_ci_pipeline_coverage
gitlab_ci_pipeline_duration_seconds
gitlab_ci_pipeline_id
gitlab_ci_pipeline_queued_duration_seconds
gitlab_ci_pipeline_run_count
gitlab_ci_pipeline_status
gitlab_ci_pipeline_timestamp
```

Let me know if there is any other data I could provide to help troubleshoot.

**Comment by cPanelRicky** [comment]
Ok, update.

I setup monitoring and checked out the parsed config and noticed it differed from what I had thought it would be.

Turns out, my issue was simply not having the `pipeline` key nested below the `pull` key for my project(Oh yaml, you never fail to remind me why I loathe you! lol).

Updating my config to the format below looks like it will have done the trick (exporters logs now show it pulling job data down).

```
server:
  listen_address: :8080
  webhook:
    enabled: true
    secret_token: $uper$ecr3t
gitlab:
  url: https://gitlab-url/
  token: $uper$ecr3t
  health_url: https://gitlab-url/-/health
projects:
  - name: awesome/product
    pull:
      pipeline:
        jobs:
          enabled: true
          from_child_pipelines:
            enabled: true
        variables:
          enabled: true
```
This is using the `docker.io/mvisonneau/gitlab-ci-pipelines-exporter:latest` docker image.
