### ISSUE TITLE
Ref not in sync

### ISSUE THREAD

**Issue by 190ba** [mvisonneau/gitlab-ci-pipelines-exporter#259]
Hello Maxime,

We're using your dashboards daily, they're really great, thank you.

This is not an issue, i guess, but a problem i can't explain.
I was looking for a branch in the dashboard and i could not find it.
In the logs, i have this :

```
"level":"info","msg":"received a pipeline webhook from GitLab for a ref, triggering metrics pull","project-name":"my/project","ref":"TRAN-655_add-things","ref-kind":"merge-request","time":"2021-04-27T15:27:06Z"
"level":"info","msg":"updated ref, associated project configuration was not in sync","project-name":"my/project","ref":"TRAN-655_add-things","time":"2021-04-27T15:34:21Z"
"level":"info","msg":"deleted ref from the store","project-name":"my/project","reason":"non-existent-ref","ref-name":"TRAN-655_add-things","time":"2021-04-27T15:34:24Z"
```

There was a pipeline with several jobs a few minutes before it says ref not in sync, then deleted from the store
In the drop down menu, i can't select this ref and see the pipeline/jobs in Grafana.

What could explain this please ?

Regards
Igor

**Comment by teochenglim** [comment]
Hi @mvisonneau 

Here is my config 

```yaml
server:
  listen_address: ":8088"
  enable_pprof: false

  metrics:
    enabled: true
    enable_openmetrics_encoding: true

  webhook:
    enabled: false

gitlab:
  url: "[redact]"
  token: [redact]

  health_url: "https://[redact]/-/health"

project_defaults:
  pull:
    refs:
      regexp: ".*"

wildcards:
  - {}
  
  ```
