### ISSUE TITLE
Pipeline runs not showing any data at 1m but does at 5m

### ISSUE THREAD

**Issue by arthurlogilab** [mvisonneau/gitlab-ci-pipelines-exporter#261]
Hey :wave:  Thanks for an awesome project, this is exactly what we've been looking for to monitor our increased workload on pipelines ! Having kubernetes, prometheus and kibana already in place, it fits in nicely ! 

I'm having trouble with some parts of the graph, let's start with the "Pipeline runs". It wasn't showing anything until I changed the `[1m]` to `[5m]` and the data appeared !?

Could this be related to the following setting I have in my `values.yaml` (helm deploy) :  

```
config:
  [snip]
  pull:
    maximum_gitlab_api_requests_per_second: 1
```
