### ISSUE TITLE
Issue when getting commits between refs

### ISSUE THREAD

**Issue by matdupont** [mvisonneau/gitlab-ci-pipelines-exporter#278]
Hello,

I have a problem on a specific project (working for another one, don't know why).
version installed: 0.4.9

```
DEBU[2021-05-28T10:47:33+02:00] comparing refs        from-ref= project-name=group/project to-ref=4c55e5a1

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xa0927e]

goroutine 25 [running]:
github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/gitlab.(*Client).GetCommitCountBetweenRefs(0xc00016dd10, 0xc0000c4360, 0x23, 0x0, 0x0, 0xc0002431c8, 0x8, 0x41d81fa647c00000, 0x0, 0x0)
	github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/gitlab/repositories.go:23 +0x41e
github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter.pullEnvironmentMetrics(0xc0000c4360, 0x23, 0x4, 0xc0000242b8, 0x16, 0xc0000c7c60, 0x1c, 0x1, 0x0, 0xc3294c, ...)
	github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter/environments.go:121 +0x805
github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter.glob..func3(0xc0000c4360, 0x23, 0x4, 0xc0000242b8, 0x16, 0xc0000c7c60, 0x1c, 0x1, 0x0, 0xc3294c, ...)
	github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter/scheduler.go:37 +0x58
reflect.Value.call(0xb2c660, 0xc61670, 0x13, 0xc30eb0, 0x4, 0xc00000d8f0, 0x1, 0x1, 0xc0005c5db0, 0x479d05, ...)
	reflect/value.go:476 +0x8e7
reflect.Value.Call(0xb2c660, 0xc61670, 0x13, 0xc00000d8f0, 0x1, 0x1, 0x0, 0xc0005c5df0, 0xc0005c5e00)
	reflect/value.go:337 +0xb9
github.com/vmihailenco/taskq/v3.(*reflectFunc).HandleMessage(0xc00016cdb0, 0xc000163860, 0xc40e08, 0x1a)
	github.com/vmihailenco/taskq/v3@v3.2.3/handler.go:78 +0x90
github.com/vmihailenco/taskq/v3.(*Task).HandleMessage(0xc00016cde0, 0xc000163860, 0x1a, 0xc00016cde0)
	github.com/vmihailenco/taskq/v3@v3.2.3/task.go:112 +0xa2
github.com/vmihailenco/taskq/v3.(*TaskMap).HandleMessage(0x1136420, 0xc000163860, 0x0, 0x0)
	github.com/vmihailenco/taskq/v3@v3.2.3/registry.go:71 +0xb3
github.com/vmihailenco/taskq/v3.(*Consumer).Process(0xc00029c540, 0xc000163860, 0xc0000a83e8, 0xc00001e0f0)
	github.com/vmihailenco/taskq/v3@v3.2.3/consumer.go:538 +0x14d
github.com/vmihailenco/taskq/v3.(*Consumer).worker(0xc00029c540, 0xd0a828, 0xc0000a83e8, 0x0)
	github.com/vmihailenco/taskq/v3@v3.2.3/consumer.go:479 +0x176
github.com/vmihailenco/taskq/v3.(*Consumer).addWorker.func1(0xc00029c540, 0xd0a828, 0xc0000a83e8, 0xc000000000)
	github.com/vmihailenco/taskq/v3@v3.2.3/consumer.go:275 +0x74
created by github.com/vmihailenco/taskq/v3.(*Consumer).addWorker
	github.com/vmihailenco/taskq/v3@v3.2.3/consumer.go:273 +0xd3
```

My config:

```
server:
  listen_address: :3031
  metrics:
    enabled: true
    enable_openmetrics_encoding: true

gitlab:
  url: <url>
  token: <token>

project_defaults:
  pull:
    environments:
      enabled: true
    pipeline:
      jobs:
        enabled: true

projects:
  - name: group/project
    pull:
      refs:
        regexp: '.*'
      environments:
        enabled: true
        name_regexp: '.*'
```

Seems like a ref is empty ? Do you have any ideas ?

Thanks !
