### ISSUE TITLE
project topics not being properly hydrated when pull scheduling is disabled

### ISSUE THREAD

**Issue by mvisonneau** [mvisonneau/gitlab-ci-pipelines-exporter#282]
I was wondering about filter by topics field, but I found another problem. When I have configuration like this
```
pull:
  projects_from_wildcards:
    on_init: false
    scheduled: true
    interval_seconds: 30

  environments_from_projects:
    on_init: false
    scheduled: true
    interval_seconds: 30

  refs_from_projects:
    on_init: false
    scheduled: true
    interval_seconds: 30

  metrics:
    on_init: false
    scheduled: true
    interval_seconds: 30

wildcards:
  -
    owner:
      name: GVIZDP01

server:
  webhook:
    enabled: true
```

everything is fine and I get metrics like this:
`gitlab_ci_pipeline_id{kind="branch",project="GVIZDP01/gitlab-tf-test",ref="master",topics="gitlab-ci-pipeline-exporter-aware,scheduled-job",variables=""} 36467`

but when I have configuration like this:
```
pull:
  projects_from_wildcards:
    on_init: false
    scheduled: false

  environments_from_projects:
    on_init: false
    scheduled: false

  refs_from_projects:
    on_init: false
    scheduled: false

  metrics:
    on_init: false
    scheduled: false

wildcards:
  -
    owner:
      name: GVIZDP01

server:
  webhook:
    enabled: true
```
I get metrics without topics:
`gitlab_ci_pipeline_id{kind="branch",project="GVIZDP01/gitlab-tf-test",ref="master",topics="",variables=""} 36467`

Is there some config option how can I get topics from webook?

_Originally posted by @gvizdpeter in https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/issues/281#issuecomment-854613972_
