### ISSUE TITLE
(Configuration) issues after upgrading from 0.4.7 to 0.5.0

### ISSUE THREAD

**Issue by dbluxo** [mvisonneau/gitlab-ci-pipelines-exporter#285]
Hi :wave:

I have updated the exporter from `0.4.7` to `0.5.0`.

Before my config looked like this:

```yaml
gitlab:
  url: https://mygitdomain.test
  health_url: https://mygitdomain.test/-/health
  enable_health_check: true
pull:
  maximum_gitlab_api_requests_per_second: 10
wildcards:
  - owner:
      name: mygroup
      kind: group
      include_subgroups: true
    pull:
      refs:
        regexp: "^(master|main|develop)$"
        max_age_seconds: 2764800 # 32 days
        from:
          merge_requests:
            enabled: true
project_defaults:
  pull:
    environments:
      enabled: false
    pipeline:
      jobs:
        enabled: true
  refs:
    regexp: "^(master|main|develop)$"
    max_age_seconds: 2764800 # 32 days
    from:
      merge_requests:
        enabled: true
```

I have adjusted the config during the upgrade to `0.5.0` as follows:

```yaml
log:
  level: info
  format: json
gitlab:
  url: https://mygitdomain.test
  health_url: https://mygitdomain.test/-/health
  enable_health_check: true
  maximum_requests_per_second: 10
wildcards:
  - owner:
      name: mygroup
      kind: group
      include_subgroups: true
    pull:
      refs:
        branches:
          enabled: true
          regexp: "^(master|main|develop)$"
          max_age_seconds: 2764800 # ~32 days
project_defaults:
  pull:
    environments:
      enabled: false
    pipeline:
      jobs:
        enabled: true
  refs:
    branches:
      enabled: true
      regexp: "^(master|main|develop)$"
      max_age_seconds: 2764800 # ~32 days
```

I noticed two things:

1. According to the documentation "Monitor pipelines related to project tags" is set to false by default. However, by me these pipelines are taken into account, I have to set this value myself explicitly to false, so e.g.:

```yaml
wildcards:
  - owner:
      name: mygroup
      kind: group
      include_subgroups: true
    pull:
      refs:
        branches:
          enabled: true
          regexp: "^(master|main|develop)$"
          max_age_seconds: 2764800 # ~32 days
        tags:
          enabled: false # <-----------------------------------------
```

2. I miss the possibility to say that only merge requests pointing to certain branches should be considered, before i could specify it like this:

```yaml
wildcards:
  - owner:
      name: mygroup
      kind: group
      include_subgroups: true
    pull:
      refs:
        regexp: "^(master|main|develop)$"
        max_age_seconds: 2764800 # 32 days
        from:
          merge_requests:
            enabled: true # <-----------------------------------------
```

Under `0.5.0` I can only either consider certain branches or merge requests in general, but no combination of these.

But maybe I haven't understood the new configuration options yet, so I would appreciate help. :blush:

**Comment by mvisonneau** [comment]
👋 hey @dbluxo, thanks for raising this issue.

1. Absolutely, `tags` are being pulled by default. I need to update the doc! 🙇
2. You are also right, we do not correlate the merge requests to the branches being configured. I wondered how it used to work in v <0.5.x though as the logic should not have changed since 🤔. Anyway, I believe it could be interesting to implement but it would involve an additional API call.

**Comment by dbluxo** [comment]
> Absolutely, tags are being pulled by default. I need to update the doc! 🙇

Thanks!

> You are also right, we do not correlate the merge requests to the branches being configured. I wondered how it used to work in v <0.5.x though as the logic should not have changed since 🤔.


Funny, before it definitely worked with the configuration above.

**Comment by dbluxo** [comment]
I think because of this part:

```
wildcards:
  pull:
    refs:
      regexp: "^(master|main|develop)$"
      max_age_seconds: 2764800 # 32 days
      from:
        merge_requests:
          enabled: true
```

Which now looks like this:

```
wildcards:
  pull:
    refs:
      branches:
        enabled: true
        regexp: "^(master|main|develop)$"
        max_age_seconds: 2764800 # ~32 days
      merge_requests:
        enabled: true
```
