### ISSUE TITLE
problem (jobs and env)

### ISSUE THREAD

**Issue by solimanr** [mvisonneau/gitlab-ci-pipelines-exporter#293]
![Captura de tela 2021-07-06 171647](https://user-images.githubusercontent.com/85713668/124661656-2bfa4680-de7e-11eb-8460-04ea03b24c9c.png)

I uploaded the exporter, but it is not pulling metrics for deploys and jobs, 
only pipepline metrics

My config:

```
log:
  level: debug
redis:
  url: redis://xxxxxx/0
gitlab:
  url: https://gitlab.xxxxxx.com/
  token: xxxxxxxx
pull:
  projects_from_wildcards:
    on_init: true
    scheduled: true
    interval_seconds: 1800

  environments_from_projects:
    on_init: true
    scheduled: true
    interval_seconds: 300

  refs_from_projects:
    on_init: true
    scheduled: true
    interval_seconds: 300

  metrics:
    on_init: true
    scheduled: true
    interval_seconds: 30

garbage_collect:
  projects:
    on_init: true
    scheduled: true
    interval_seconds: 14400

  environments:
    on_init: true
    scheduled: true
    interval_seconds: 14400

  refs:
    on_init: true
    scheduled: true
    interval_seconds: 1800

  metrics:
    on_init: true
    scheduled: true
    interval_seconds: 300

project_defaults:
  output_sparse_status_metrics: true

  pull:
    environments:
      enabled: true
      regexp: ".*"
      exclude_stopped: true

    refs:
      branches:
        enabled: true
        regexp: "^main|master$"

        most_recent: 0

        max_age_seconds: 0
        exclude_deleted: true

      tags:
        enabled: true
        regexp: ".*"
        most_recent: 0
        max_age_seconds: 0
        exclude_deleted: true
      merge_requests:
        enabled: true
        most_recent: 0
        max_age_seconds: 0

    pipeline:
      jobs:
        enabled: true

        from_child_pipelines:
          enabled: true
        
        runner_description:
          enabled: true
          aggregation_regexp: shared-runners-manager-(\d*)\.gitlab\.com

      variables:
        enabled: true
        regexp: ".*"

projects:
  - name: dev/xxxxxx

    pull:
      environments:
        enabled: true
        regexp: ".*"
        exclude_stopped: true

      refs:
        branches:
          enabled: true
          regexp: "^main|master$"
          most_recent: 0
          max_age_seconds: 0
          exclude_deleted: true

        tags:
          enabled: true
          regexp: ".*"
          most_recent: 0
          max_age_seconds: 0
          exclude_deleted: true

        merge_requests:
          enabled: true
          most_recent: 0
          max_age_seconds: 0

      pipeline:
        jobs:
          enabled: true

          from_child_pipelines:
            enabled: true

          runner_description:
            enabled: true
            aggregation_regexp: shared-runners-manager-(\d*)\.gitlab\.com

        variables:
          enabled: true
          regexp: ".*"

wildcards:
  - owner:
      name: dev
      kind: group
      include_subgroups: true
    search: ''
    archived: true
    pull:
      environments:
        enabled: true
        regexp: ".*"
        exclude_stopped: true

      refs:
        branches:
          enabled: true
          regexp: "^main|master$"
          most_recent: 0
          max_age_seconds: 0
          exclude_deleted: true

        tags:
          enabled: true
          regexp: ".*"
          most_recent: 0
          max_age_seconds: 0
          exclude_deleted: true

        merge_requests:
          enabled: true
          most_recent: 0
          max_age_seconds: 0

      pipeline:
        jobs:
          enabled: true

          from_child_pipelines:
            enabled: true

          runner_description:
            enabled: true
            aggregation_regexp: shared-runners-manager-(\d*)\.gitlab\.com

        variables:
          enabled: true
          regexp: ".*"
```
