### ISSUE TITLE
config flag provided but not defined

### ISSUE THREAD

**Issue by paulbygrave** [mvisonneau/gitlab-ci-pipelines-exporter#299]
Been using a much older version of the image for over a year, figured it was time to update.

```
docker run -it --rm \ 
    --name gitlab-ci-pipelines-exporter \
    -v /etc/gitlab-ci-pipelines-exporter/config.yml:/etc/config.yml \
    -p 8081:8080 mvisonneau/gitlab-ci-pipelines-exporter:latest \
    --config /etc/config.yml
```

Exactly the same command i used to run and I havent changed anything in the config file or the config file path etc.
Used to work fine but with the new container I get:

```
Incorrect Usage. flag provided but not defined: -config

NAME:
   gitlab-ci-pipelines-exporter - Export metrics about GitLab CI pipelines statuses

USAGE:
   gitlab-ci-pipelines-exporter [global options] command [command options] [arguments...]

VERSION:
   0.5.1-5-g519f8b2

COMMANDS:
   run      start the exporter
   monitor  display information about the currently running exporter
   help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --internal-monitoring-listener-address value, -m value  internal monitoring listener address [$GCPE_INTERNAL_MONITORING_LISTENER_ADDRESS]
   --help, -h                                              show help (default: false)
   --version, -v                                           print the version (default: false)
flag provided but not defined: -config
```

Demo config in the quickstart guide doesn't seem to be wildly different to what I have at the moment:

 ```
# URL and Token with sufficient permissions to access your GitLab's projects
# pipelines informations
gitlab:
  url: <REDACTED>
  token: <REDACTED>                         # Gitlab access token
  skip_tls_verify: true                           # disable TLS verification

# Global rate limit for the GitLab API request/sec
maximum_gitlab_api_requests_per_second: 10

# Custom waiting time between polls for projects, their refs and pipelines (in seconds, optional)
projects_polling_interval_seconds: 1800 # only used for wildcards
refs_polling_interval_seconds: 300
pipelines_polling_interval_seconds: 60
pipelines_max_polling_interval_seconds: 1800 # when no pipeline exists for a given ref, the exporter will exponentially backoff up to this value

# Whether to attempt retrieving refs from pipelines when the exporter starts (default: false)
on_init_fetch_refs_from_pipelines: false
# Maximum number of pipelines to analyze per project to search for refs on init (default: 100)
on_init_fetch_refs_from_pipelines_depth_limit: 100

# Search for projects globally
# As configured below will cover all projects in GitLab (master branches only)
wildcards:
  - {}
```

Anyone able to assist?
