### ISSUE TITLE
Missing projects in /metrics when using wildcards searching

### ISSUE THREAD

**Issue by chiaminchuang** [mvisonneau/gitlab-ci-pipelines-exporter#315]
Hello, 

My exporter failed to expose all projects metrics in `/metrics` using wildcards searching. 
Here is my GitLab group structure,
```
# group structure example
/
+-- foo
|   +-- share
|      +-- my_project
|      +-- other_project
|   +-- private
|      +-- private_project1
|      +-- private_project2
```
I set the wildcards search name to an upper-level group (**foo**), and the exporter cannot expose all the projects in subgroup **share** in `/metrics`. However, I use a lower-level subgroup **share** as the wildcards search name, the exporter can expose all the projects under the subgroup **share** in `/metrics`. 
Both configurations can list all projects, but only the latter can expose all the projects in `/metrics`.  
Is there any limitation on the number of exposed jobs?

Below is my exporter config,
```
project_defaults:
  pull:
    refs:
      branches:
        regexp: ".*"
    
    pipeline:
      jobs:
        enabled: true

wildcards:
  - owner:
      name: foo/share   # Got my_project in /metrics correctly
      # name: foo       # Fail to get my_project in /metrics

      kind: group
      include_subgroups: true

    search: ''
    pull:
      refs:
        branches:
          regexp: ".*"
          
      pipeline:
        jobs:
          enabled: true
```

Below is the partial exporter logs about the my_project, and there is nothing information about my_project in `/metrics`
```
...

time="2021-08-19T01:30:12Z" level=info msg="discovered new project" project-name=foo/share/my_project wildcard-archived=false wildcard-owner-include-subgroups=true wildcard-owner-kind=group wildcard-owner-name=foo wildcard-search=

...

time="2021-08-19T01:36:43Z" level=trace msg="listing project pipelines" page=1 project-name=foo/share/my_project
time="2021-08-19T01:36:44Z" level=trace msg="found ref" project-name=foo/share/my_project ref=1 ref-kind=merge-request
time="2021-08-19T01:36:44Z" level=info msg="discovered new ref" project-name=foo/share/my_project ref=1.0.5.0 ref-kind=tag
time="2021-08-19T01:36:44Z" level=info msg="discovered new ref" project-name=foo/share/my_project ref=1 ref-kind=merge-request
time="2021-08-19T01:36:44Z" level=info msg="discovered new ref" project-name=foo/share/my_project ref=dev ref-kind=branch
time="2021-08-19T01:36:44Z" level=info msg="discovered new ref" project-name=foo/share/my_projectref=master ref-kind=branch
time="2021-08-19T01:36:44Z" level=info msg="discovered new ref" project-name=foo/share/my_project ref=1.0.10.0 ref-kind=tag
time="2021-08-19T01:36:44Z" level=info msg="discovered new ref" project-name=foo/share/my_project ref=1.0.9.0 ref-kind=tag
time="2021-08-19T01:36:44Z" level=info msg="discovered new ref" project-name=foo/share/my_project ref=1.0.7.0 ref-kind=tag
time="2021-08-19T01:36:44Z" level=info msg="discovered new ref" project-name=foo/share/my_project ref=1.0.6.0 ref-kind=tag

...
```
The exporter did discover my_project, but no my_project metrics in `/metrics`.
Thank you for your great exporter.
