### ISSUE TITLE
gitlab-ci-pipelines-exporter causes the load of gitlab to be too high

### ISSUE THREAD

**Issue by OPSTime** [mvisonneau/gitlab-ci-pipelines-exporter#316]
gitlab-ci-pipelines-exporter causes the load of gitlab to be too high. 
Is there anything that can be optimized？

**cat gitlab-ci-pipelines-exporter.yml**
```
log:
  level: debug
  format: text

server:
  listen_address: 0.0.0.0:8080
  enable_pprof: false
  metrics:
    enabled: true

gitlab:
  url: https://gitlab.example.com
  token: xxxx

pull:
  projects_from_wildcards:
    on_init: false
    scheduled: false
  environments_from_projects:
    on_init: false
    scheduled: false
  refs_from_projects:
    on_init: true
    scheduled: true
    interval_seconds: 900
  metrics:
    on_init: true
    scheduled: true
    interval_seconds: 300

# Pull jobs related metrics on all projects
project_defaults:
  pull:
    pipeline:
      jobs:
        enabled: true

projects:
  - name: wisers-front-end/next-datacenter
    pull:
      environments:
        enabled: true
      refs:
        regexp: ".*"

......
```
