### ISSUE TITLE
"listen: unknown network " after upgrading to 0.5.1

### ISSUE THREAD

**Issue by Vitune** [mvisonneau/gitlab-ci-pipelines-exporter#317]
Good day.

After upgrading to 0.5.1 started getting an error:
```
error="listen: unknown network "
```
0.5.0 works fine

my config:
```
gitlab:
  url: <gitlab>
  token: <token>
server:
  listen_address: :8888
wildcards:
  - {}
```

how i run the binary:
```
gitlab-ci-pipelines-exporter run -c /etc/gitlab-ci-pipelines/config.yml
```
