### ISSUE TITLE
Error with export metrics

### ISSUE THREAD

**Issue by IlyaNakhaichuk** [mvisonneau/gitlab-ci-pipelines-exporter#320]
How can I solve this problem? the metrics start downloading, but after 5 minutes it reboots, I see an error in the logs, and so it constantly restarts.
It is not clear what this error refers to:` panic: runtime error: invalid memory address or nil pointer dereference`

Could you tell me where to look, what to change?

ON KUBE:
```
NAME                                            CPU(cores)   MEMORY(bytes)   
gitlab-ci-pipelines-exporter-866fc7c6fd-x8rd7   55m          22Mi            
gitlab-ci-pipelines-exporter-redis-master-0     12m          9Mi  
```

CONFIG:
```
config:
  gitlab:
    url: https://xxx
    token: "XXX"
  projects:
    - name: xxx
      # Here are all the project parameters which can be overriden (optional)
      pull:
        environments:
          # Whether or
          # not to pull project environments & their deployments
          # (optional, default: false)
          enabled: false

          # Filter out by name environments to include
          # (optional, default: ".*")
          regexp: ".*"

          # Do not export metrics for stopped environments
          # (optional, default: true)
          exclude_stopped: true

        refs:
          branches:
            # Monitor pipelines related to project branches
            # (optional, default: true)
            enabled: true

            # Filter for branches to include
            # (optional, default: "^main|master$" -- main/master branches)
            regexp: ".*"

            # Only keep most 'n' recently updated branches
            # (optional, default: 0 -- disabled/keep every branch matching the regexp)"
            most_recent: 20

            # If the age of the most recently updated pipeline for the branch is greater than
            # this value, the pipeline metrics won't get exported (optional, default: 0 (disabled))
            max_age_seconds: 604800

            # If set to false, it will continue to export metrics for the branch even
            # if it has been deleted (optional, default: true)
            exclude_deleted: true

          tags:
            # Monitor pipelines related to project tags
            # (optional, default: true)
            enabled: false

            # Filter for tags to include
            # (optional, default: ".*" -- all tags)
            regexp: ".*"

            # Only keep most 'n' recently updated tags
            # (optional, default: 0 -- disabled/keep every tag matching the regexp)"
            most_recent: 20

            # If the age of the most recently updated pipeline for the tag is greater than
            # this value, the pipeline metrics won't get exported (optional, default: 0 (disabled))
            max_age_seconds: 604800

            # If set to false, it will continue to export metrics for the tag even
            # if it has been deleted (optional, default: true)
            exclude_deleted: true

          merge_requests:
            # Monitor pipelines related to project merge requests
            # (optional, default: false)
            enabled: true

            # Only keep most 'n' recently updated merge requests
            # (optional, default: 0 -- disabled/keep every merge request)
            most_recent: 20

            # If the age of the most recently updated pipeline for the merge request is greater than
            # this value, the pipeline metrics won't get exported (optional, default: 0 (disabled))
            max_age_seconds: 604800

        pipeline:
          jobs:
            # Whether to attempt retrieving job level metrics from pipelines.
            # Increases the number of outputed metrics significantly!
            # (optional, default: false)
            enabled: true

            from_child_pipelines:
              # Collect jobs from subsequent child/downstream pipelines
              # (optional, default: true)
              enabled: true

            runner_description:
              # Export the description of the runner which ran the job
              # (optional, default: true)
              enabled: true

              # Whenever the description of a runner will match this regexp
              # The regexp will be used as the value of the runner description instead
              # (optional, default: "shared-runners-manager-(\d*)\.gitlab\.com")
              aggregation_regexp: ".*"

          variables:
            # Fetch pipeline variables in a separate metric (optional, default: false)
            enabled: true

            # Filter pipelines variables to include
            # (optional, default: ".*", all variables)
            regexp: ".*"

ingress:
  # ingress.enabled -- deploy a ingress to access the exporter pod(s) /webhook endpoint
  enabled: true

  # ingress.annotations -- additional annotations for the ingress resource
  annotations:
    # kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

  # ingress.path -- path on the exporter to point the root of the ingress
  path: /metrics

  # ingress.pathType -- pathType for the ingress
  pathType: Prefix

  service:
    port:
    # ingress.service.port.name -- service port for the ingress
      name: http

  # ingress.hosts -- ingress hosts
  hosts:
    - xxxl.com

  # ingress.tls -- ingress tls hosts config
  tls:
    - hosts:
        - xxx.com
      secretName: xxx

livenessProbe:
  httpGet:
    path: /metrics
    port: 8080

readinessProbe:
  httpGet:
    path: /metrics
    port: 8080
  initialDelaySeconds: 5
  timeoutSeconds: 5
  failureThreshold: 3
  periodSeconds: 30

resources:
  requests:
    cpu: 100m
    memory: 256Mi
```

LOG:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x87d1f7]

goroutine 70 [running]:
github.com/go-redis/redis/v8/internal/pool.(*ConnPool).waitTurn(0xc000110f00, 0x0, 0x0, 0x7fdebccd31d8, 0x0)
	github.com/go-redis/redis/v8@v8.9.0/internal/pool/pool.go:273 +0x37
github.com/go-redis/redis/v8/internal/pool.(*ConnPool).Get(0xc000110f00, 0x0, 0x0, 0xc000d87830, 0x87a882, 0x123dbf0)
	github.com/go-redis/redis/v8@v8.9.0/internal/pool/pool.go:234 +0x52
github.com/go-redis/redis/v8.(*baseClient)._getConn(0xc00053cac0, 0x0, 0x0, 0x7fdebccd31d8, 0xc000d87898, 0x40db9b)
	github.com/go-redis/redis/v8@v8.9.0/redis.go:207 +0x4c
github.com/go-redis/redis/v8.(*baseClient).getConn(0xc00053cac0, 0x0, 0x0, 0xf, 0x0, 0x0)
	github.com/go-redis/redis/v8@v8.9.0/redis.go:195 +0x66
github.com/go-redis/redis/v8.(*baseClient).withConn(0xc00053cac0, 0x0, 0x0, 0xc0011e4a20, 0x0, 0x0)
	github.com/go-redis/redis/v8@v8.9.0/redis.go:293 +0x127
github.com/go-redis/redis/v8.(*baseClient)._generalProcessPipeline(0xc00053cac0, 0x0, 0x0, 0xc000bf9580, 0x4, 0x4, 0xc000a62be0, 0x10, 0xbddd40)
	github.com/go-redis/redis/v8@v8.9.0/redis.go:449 +0x113
github.com/go-redis/redis/v8.(*baseClient).generalProcessPipeline(0xc00053cac0, 0x0, 0x0, 0xc000bf9580, 0x4, 0x4, 0xc000a62be0, 0x40db9b, 0xc0003ecea0)
	github.com/go-redis/redis/v8@v8.9.0/redis.go:429 +0x77
github.com/go-redis/redis/v8.(*baseClient).processTxPipeline(...)
	github.com/go-redis/redis/v8@v8.9.0/redis.go:421
github.com/go-redis/redis/v8.hooks.processPipeline.func1(...)
	github.com/go-redis/redis/v8@v8.9.0/redis.go:94
github.com/go-redis/redis/v8.hooks.withContext(...)
	github.com/go-redis/redis/v8@v8.9.0/redis.go:133
github.com/go-redis/redis/v8.hooks.processPipeline(0x0, 0x0, 0x0, 0x0, 0x0, 0xc000bf9580, 0x4, 0x4, 0xc000d87ce0, 0x8, ...)
	github.com/go-redis/redis/v8@v8.9.0/redis.go:93 +0x393
github.com/go-redis/redis/v8.hooks.processTxPipeline(0x0, 0x0, 0x0, 0x0, 0x0, 0xc000245a20, 0x2, 0x2, 0xc000d87ce0, 0x0, ...)
	github.com/go-redis/redis/v8@v8.9.0/redis.go:129 +0x2b7
github.com/go-redis/redis/v8.(*Client).processTxPipeline(...)
	github.com/go-redis/redis/v8@v8.9.0/redis.go:629
github.com/go-redis/redis/v8.(*Pipeline).Exec(0xc0004d3720, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/go-redis/redis/v8@v8.9.0/pipeline.go:115 +0x102
github.com/vmihailenco/taskq/v3/redisq.(*Queue).Release(0xc0000e2000, 0xc00018ed00, 0x0, 0x1)
	github.com/vmihailenco/taskq/v3@v3.2.4/redisq/queue.go:232 +0x1ae
github.com/vmihailenco/taskq/v3.(*Consumer).fetchMessages(0xc000150000, 0xd94408, 0xc00002a048, 0xc0005407d0, 0x3edd410c00, 0x0, 0x0, 0x0)
	github.com/vmihailenco/taskq/v3@v3.2.4/consumer.go:438 +0x276
github.com/vmihailenco/taskq/v3.(*Consumer).fetcher(0xc000150000, 0xd94408, 0xc00002a048, 0x0)
	github.com/vmihailenco/taskq/v3@v3.2.4/consumer.go:393 +0x1c5
github.com/vmihailenco/taskq/v3.(*Consumer).addFetcher.func1(0xc000150000, 0xd94408, 0xc00002a048, 0xc000000000)
	github.com/vmihailenco/taskq/v3@v3.2.4/consumer.go:294 +0x74
created by github.com/vmihailenco/taskq/v3.(*Consumer).addFetcher
	github.com/vmihailenco/taskq/v3@v3.2.4/consumer.go:292 +0xd3

```
