### ISSUE TITLE
msg="received a non supported event type as a webhook" event-type="*gitlab.JobEvent

### ISSUE THREAD

**Issue by OPSTime** [mvisonneau/gitlab-ci-pipelines-exporter#332]
# gitlab-ci-pipelines-exporter  log:
```
Sep 25 00:40:44 test gitlab-ci-pipelines-exporter[6782]: time="2021-09-25T00:40:44+08:00" level=info msg="starting 'metrics' garbage collection"
Sep 25 00:40:44 test gitlab-ci-pipelines-exporter[6782]: time="2021-09-25T00:40:44+08:00" level=info msg="ending 'metrics' garbage collection"
Sep 25 00:40:45 test gitlab-ci-pipelines-exporter[6782]: time="2021-09-25T00:40:45+08:00" level=warning msg="received a non supported event type as a webhook" event-type="*gitlab.JobEvent" ip-address="192.168.1.10:36410" user-agent=
```

# /metrics
```
# HELP gitlab_ci_pipeline_coverage Coverage of the most recent pipeline
# TYPE gitlab_ci_pipeline_coverage gauge
gitlab_ci_pipeline_coverage{kind="branch",project="test-group/test-project",ref="devops",topics="",variables=""} 0
# HELP gitlab_ci_pipeline_duration_seconds Duration in seconds of the most recent pipeline
# TYPE gitlab_ci_pipeline_duration_seconds gauge
gitlab_ci_pipeline_duration_seconds{kind="branch",project="test-group/test-project",ref="devops",topics="",variables=""} 0
# HELP gitlab_ci_pipeline_id ID of the most recent pipeline
# TYPE gitlab_ci_pipeline_id gauge
gitlab_ci_pipeline_id{kind="branch",project="test-group/test-project",ref="devops",topics="",variables=""} 128489
# HELP gitlab_ci_pipeline_run_count Number of executions of a pipeline
# TYPE gitlab_ci_pipeline_run_count counter
gitlab_ci_pipeline_run_count{kind="branch",project="test-group/test-project",ref="devops",topics="",variables=""} 1
# HELP gitlab_ci_pipeline_status Status of the most recent pipeline
# TYPE gitlab_ci_pipeline_status gauge
gitlab_ci_pipeline_status{kind="branch",project="test-group/test-project",ref="devops",status="canceled",topics="",variables=""} 0
gitlab_ci_pipeline_status{kind="branch",project="test-group/test-project",ref="devops",status="created",topics="",variables=""} 0
gitlab_ci_pipeline_status{kind="branch",project="test-group/test-project",ref="devops",status="failed",topics="",variables=""} 0
gitlab_ci_pipeline_status{kind="branch",project="test-group/test-project",ref="devops",status="manual",topics="",variables=""} 0
gitlab_ci_pipeline_status{kind="branch",project="test-group/test-project",ref="devops",status="pending",topics="",variables=""} 0
gitlab_ci_pipeline_status{kind="branch",project="test-group/test-project",ref="devops",status="preparing",topics="",variables=""} 0
gitlab_ci_pipeline_status{kind="branch",project="test-group/test-project",ref="devops",status="running",topics="",variables=""} 1
gitlab_ci_pipeline_status{kind="branch",project="test-group/test-project",ref="devops",status="scheduled",topics="",variables=""} 0
gitlab_ci_pipeline_status{kind="branch",project="test-group/test-project",ref="devops",status="skipped",topics="",variables=""} 0
gitlab_ci_pipeline_status{kind="branch",project="test-group/test-project",ref="devops",status="success",topics="",variables=""} 0
gitlab_ci_pipeline_status{kind="branch",project="test-group/test-project",ref="devops",status="waiting_for_resource",topics="",variables=""} 0
# HELP gitlab_ci_pipeline_timestamp Timestamp of the last update of the most recent pipeline
# TYPE gitlab_ci_pipeline_timestamp gauge
gitlab_ci_pipeline_timestamp{kind="branch",project="test-group/test-project",ref="devops",topics="",variables=""} 1.632501375e+09
# HELP promhttp_metric_handler_errors_total Total number of internal errors encountered by the promhttp metric handler.
# TYPE promhttp_metric_handler_errors_total counter
promhttp_metric_handler_errors_total{cause="encoding"} 0
promhttp_metric_handler_errors_total{cause="gathering"} 0
```

# configure:
```
# Log configuration
log:
  # Set the logging level
  # allowed values: trace, debug, info, warning, error, fatal or panic
  # (optional, default: info)
  level: debug

  format: text

server:
  # [address:port] to make the process listen
  # upon (optional, default: :8080)
  listen_address: 0.0.0.0:8080
  
  # Enable profiling pages
  enable_pprof: false
  
  metrics:
    # Enable /metrics endpoint (optional, default: true)
    enabled: true

  webhook:
    enabled: true
    secret_token: xxxxxxxxxxxxxxxx

gitlab:
  url: https://test.example.com
  token: xxxxxxxxxxxx

pull:
  projects_from_wildcards:
    on_init: false
    scheduled: false

  environments_from_projects:
    on_init: false
    scheduled: false

  refs_from_projects:
    on_init: false
    scheduled: false

  metrics:
    on_init: false
    scheduled: false

projects:
  - name: test-group/test-project
    pull:
      refs:
        regexp: ".*"
```
