### ISSUE TITLE
Pipelines export seems to not poll for pipleines

### ISSUE THREAD

**Issue by Cobra1978** [mvisonneau/gitlab-ci-pipelines-exporter#34]
Hi.

I've installed the exporter with a simple configuration.

In logs i see that he found projects, but i get no info about pipelines, and in the logs there is no information about the problem.

Teh token configuration must be right because i've used it with timoschwazer gitlab-monitor, and it worked.

Confgiuration:
```
# URL and Token with sufficient permissions to access your GitLab's projects
# pipelines informations
gitlab:
  url: [omitted]
  token: [omitted]
  health_url: https://gitlab.mag-news.it/-/health  # Alternative URL for determining health of GitLab API (readiness probe)
  skip_tls_verify: false                           # disable TLS verification

# Custom waiting time between polls for projects, their refs and pipelines (in seconds, optional)
projects_polling_interval_seconds: 1800 # only used for wildcards
refs_polling_interval_seconds: 300
pipelines_polling_interval_seconds: 60
pipelines_max_polling_interval_seconds: 1800 # when no pipeline exists for a given ref, the exporter will exponentially backoff up to this value

# Default regexp for parsing the refs (branches and tags) to monitor (optional, default to master)
# default_refs: "^master$"

# The list of the projects you want to monitor

# Dynamically fetch projects to monitor using a wildcard
wildcards:
  # Fetch projects belonging to a group and potentially its subgroups
  - owner:
      name: dms
      kind: group
      include_subgroups: true # optional (default: false)
    refs: "^master$"
    search: '' # optional (defaults to '')
```
