### ISSUE TITLE
Missing metrics when integrating grafana dashboard 13328/13329

### ISSUE THREAD

**Issue by rgaoistheone** [mvisonneau/gitlab-ci-pipelines-exporter#347]
Hi everyone , 
I'm new to this exporter and just curious why I'm missing a bunch of metrics like,

gitlab_ci_environment_*
gitlab_ci_pipeline_job_*

![image](https://user-images.githubusercontent.com/5696899/136659239-041f68fc-6ec9-4e60-a7e3-befc311f4a3e.png)

Here is configurations
```
config:
  gitlab:
    url: https://git.com/
    # You can also configure the token using --gitlab-token
    # or the $GCPE_GITLAB_TOKEN environment variable
    token: token_val
  wildcards:
    - {}

serviceMonitor:
  # serviceMonitor.enabled -- deploy a serviceMonitor resource
  enabled: true
  labels:
    release: kube-prometheus-stack
```
helm list -n gitlab-exporter
NAME                        	NAMESPACE      	REVISION	UPDATED                             	STATUS  	CHART                             	APP VERSION
gitlab-ci-pipelines-exporter	gitlab-exporter	1       	2021-10-09 20:49:06.615196 +0800 CST	deployed	gitlab-ci-pipelines-exporter-0.2.8	v0.5.2

**Comment by ixxeL2097** [comment]
Hi guys,

I have same issue, not getting environment and jobs metrics, only pipelines metrics are ok. I use this config:
```
config:
  project_defaults:
    pull:
      environments:
        enabled: true
      pipeline:
        jobs:
          enabled: true
          from_child_pipelines:
            enabled: true
          runner_description:
            enabled: true
  projects:
    - name: group-A/apps/example
    - name: group-A/manifests/example
  wildcards:
    - owner:
        name: group-A
        kind: group
        include_subgroups: true
```

any idea ?
