### ISSUE TITLE
How to set up multiple wildcards.owner  ?

### ISSUE THREAD

**Issue by jicki** [mvisonneau/gitlab-ci-pipelines-exporter#367]
How to set up multiple wildcards.owner  ? 

```yaml
wildcards:
  - 
    owner:
      name: test1
      kind: group
```

```yaml
wildcards:
  - 
    owner:
      name: test2
      kind: group

```

**Comment by mvisonneau** [comment]
```yaml
wildcards:
  - owner:
       name: test1
       kind: group
  - owner:
       name: test2
       kind: group
```
