### ISSUE TITLE
Pull all environments but ref to only one branch (main)

### ISSUE THREAD

**Issue by ajleandroaj** [mvisonneau/gitlab-ci-pipelines-exporter#375]
Hi.

I have my CI/CD based at one branch by environment, and I'm using your `example/quickstart` as a base project.

My `gitlab-ci-pipelines-exporter.yml`:
```yml
...
projects:
  - name: some-author/some-project
    pull:
      environments:
        enabled: true
      refs: 
        branches:
          regexp: "^main$"
...
```

The actual result:
![Actual result](https://user-images.githubusercontent.com/13999339/144419885-8767b804-a853-40d6-9011-4913eb6d46f0.png)

I would like to pull all the information of all environments, but the Ref should be from only one branch, the `Main`.
The expected result:
![Expected result](https://user-images.githubusercontent.com/13999339/144419973-d8af12e8-0949-44d4-9da0-331b397b245e.png)

That is even possible?
Thanks!

**Comment by zemkogabor** [comment]
I have a similar problem.

With this config:
```
project_defaults:
  pull:
    refs:
      branches:
        regexp: ".*"
```

Only `master` branches refs founded by exporter.  The configuration correctly loaded, I checked with `gitlab-ci-pipelines-exporter monitor` CLI tool. It looks like the exporter ignoring custom config.
