### ISSUE TITLE
Need a bare minimum config file which can populate metrics in these dashboards

### ISSUE THREAD

**Issue by satish-chef** [mvisonneau/gitlab-ci-pipelines-exporter#378]
Hello,

I want a bare minimum `config.yml` file which helps me to populate all the metrics in the three dashboards which are present in this [link](https://grafana.com/orgs/mvisonneau).

The current config file that I am using is generating a lot of logs in Gitlab which I am looking to avoid:
```
log:
  level: debug
gitlab:
  url: https://gitlab.com
  # You can also configure the token using --gitlab-token
  # or the $GCPE_GITLAB_TOKEN environment variable
  token: abcdefgh
projects:
  - name: abc/code1
  - name: abc/code2
  - name: abc/code3
  - name: abc/code4
  - name: abc/code5
  - name: abc/code6
  - name: abc/code7

wildcards:
  - owner:
      name: abc
      kind: group
# Pull jobs related metrics on all projects
project_defaults:
  pull:
    environments:
      enabled: true
    pipeline:
      jobs:
        enabled: true
        from_child_pipelines:
          enabled: true
        runner_description:
          # Export the description of the runner which ran the job
          # (optional, default: true)
          enabled: true
      variables:
        # Fetch pipeline variables in a separate metric (optional, default: false)
        enabled: false
    refs:
      branches:
        # Monitor pipelines related to project branches
        # (optional, default: true)
        enabled: true
      tags:
        # Monitor pipelines related to project tags
        # (optional, default: true)
        enabled: true
      merge_requests:
        # Monitor pipelines related to project merge requests
        # (optional, default: false)
        enabled: false
```

@mvisonneau ^^

**Comment by mvisonneau** [comment]
👋 hey @satish-chef, if you are looking to reduce the amount of requests whilst keeping the same functionalities, have a look at this example leveraging webhooks: https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/main/examples/webhooks/gitlab-ci-pipelines-exporter.yml

**Comment by satish-chef** [comment]
@mvisonneau I reverted back to using below config file:

```
log:
  level: debug
gitlab:
  url: https://example.gitlab.com
  # You can also configure the token using --gitlab-token
  # or the $GCPE_GITLAB_TOKEN environment variable
  token: ****************
projects:
  - name: abc/repo1
  - name: abc/repo2
  - name: abc/repo3
  - name: abc/repo4
  - name: abc/repo5
  - name: abc/repo6
  - name: abc/repo7
  - name: abc/repo8
  - name: abc/repo9
  - name: abc/repo10
  - name: abc/repo11
  - name: abc/repo12
  - name: abc/repo13
  - name: abc/repo14
  - name: abc/repo15

wildcards:
  - owner:
      name: abc
      kind: group
# Pull jobs related metrics on all projects
project_defaults:
  pull:
    environments:
      enabled: true
    pipeline:
      jobs:
        enabled: true
        from_child_pipelines:
          enabled: true
    refs:
      branches:
        # Monitor pipelines related to project branches
        # (optional, default: true)
        enabled: true
      merge_requests:
        # Monitor pipelines related to project merge requests
        # (optional, default: false)
        enabled: false
```

But still I am seeing that metrics are not getting populated for below two dashboards:

1. GitLab CI jobs - https://grafana.com/grafana/dashboards/13328
2. GitLab CI pipelines - https://grafana.com/grafana/dashboards/10620

The project/repo name does not show up in the "project" drop down list.  Can you please let me know what could be the issue here.  Do I need to enable some settings for these repositories in Gitlab ?

![image](https://user-images.githubusercontent.com/9479581/152718803-d0b53f74-9d7c-443d-8eff-52fc2e96276b.png)
