### ISSUE TITLE
Wildcard + Search

### ISSUE THREAD

**Issue by ancordier** [mvisonneau/gitlab-ci-pipelines-exporter#391]
Suppose I have this tree :

 * foo
   * project1
   * project2
 * foo2
   * project3
   * project4

I want to monitor the project 1, 2 and 3 but not the 4th.

```
- owner: { name: foo, kind: group, include_subgroups: true }
- owner: { name: foo2, kind: group, include_subgroups: true }
  search: 'project3'
```

I don't get any project in the foo2 group with this syntax ... How can I do ?

**Comment by mvisonneau** [comment]
```yaml
wildcards:
  - owner: { name: foo, kind: group, include_subgroups: true }

projects:
  - { name: foo2/project3 }
```

would something like this be manageable? 🤷 ☝️
