### ISSUE TITLE
Readiness probe failed: HTTP probe failed with statuscode: 503

### ISSUE THREAD

**Issue by kaushique** [mvisonneau/gitlab-ci-pipelines-exporter#393]
Hi Team,
i've setup gitlab ci pipeline exporter using helm chart way , but when i see the pod events it says "Readiness probe failed: HTTP probe failed with statuscode: 503" 
Because of this the endpoint is not coming and i'm unable to view metrics at /metrics at port 8080 
I've made sure no other app service is exposed at 8080 .
it's reading the data from gitlab but status of the pod remains 0/1 running 
how do i overcome it ? i tried increasing the initial delay and failure threshold for readiness probe but no luck 

Any help is appreciated and Thanks in advance

**Comment by mvisonneau** [comment]
👋 can you share the logs of the pods when this situation occurs? Preferably with log.level set to debug or trace?

**Comment by hexa2k9** [comment]
We experienced the same and after deploying the Exporter like a million times through Helm with different options this worked for us:

```
[...]
config:
  gitlab:
    enable_tls_verify: true
    enable_health_check: true
    maximum_requests_per_second: 60
    token: <token>
    url: https://git.host.name/
[...]
```

We had config.gitlab.url in our values.yaml without the trailing Slash, but it seems to be required.

So mind the trailing Slash in the GitLab URL, that fixed it for us.
