### ISSUE TITLE
additional project metrics as enhancement

### ISSUE THREAD

**Issue by crazymushrooms** [mvisonneau/gitlab-ci-pipelines-exporter#408]
Your gitlab-ci-pipeline-exporter is a great tool and saved us a lot of trouble while monitoring the pipelines.
Although as the tool name proposes it is "pipeline" exporter we would like to get more stats from gitlab API without integrating additional tools :)
So for example we are interested to get metrics on project branches & merge requests.

I think of something like:

```
gitlab_ci_project_branch{project="foo/bar", ref="main", status="default", protected="true", merged="false"} 1
gitlab_ci_project_branch{project="foo/bar", ref="merge-request/foo", status="deleted", protected="true", merged="true"} 1
gitlab_ci_project_branch{project="foo/bar", ref="test/foo", status="stale", protected="false", merged="false"} 1
gitlab_ci_project_branch{project="foo/bar", ref="feature/foo", status="active", protected="true", merged="false"} 1


gitlab_ci_merge_request{project="foo/bar", ref="!1", state="closed", source_branch="merge-request/foo"} 1
gitlab_ci_merge_request{project="foo/bar", ref="!2", state="opened", source_branch="merge-feature/foo"} 1
```

with some kind of config as:
```
project_default:
  stats:
    enabled: true
    archived: false
  branches:
    ref:
     # or "*" for all
      regexp: "^main|feature.*$" 
    deleted: false
    stale: false
    limit: 5
    # additional_labels: ["commit.short_id", "web_url"]
  merge_requests:
    enabled: true
    limit: 5
    # when no status provided - fetch all
    status: ["opened", "locked"]
    # additional_labels: ["created_at", "merged_by"]
```
