### ISSUE TITLE
Can't pull single branch from single project

### ISSUE THREAD

**Issue by z3r0g2017** [mvisonneau/gitlab-ci-pipelines-exporter#414]
Hi,
I am unable to pull a single named branch from a single named project. I am on glcpe 0.5.2. I have a branch named `foo/bar` and would like to retrieve it from a project named `mno`. This project is contained under a group/subgroup path `abc/def/ghi/jkl`. When I run gcpe, It logs `ref-count=0` for` kind="branch"`.

My config file is as below
```
gitlab:
  url: https://gitlab.com
  token: foobaz

log:
  level: debug

project_defaults:
  pull:
    refs:
      branches:
        enabled: true
      tags:
        enabled: false
      regexp: "^foo/bar$"

      max_age_seconds: 7776000 # for commit ids within the last 3 months

projects:
  - name: abc/def/ghi/jkl/mno
```
Please help me troubleshoot and make it work.
TIA.
