### ISSUE TITLE
TLS Verfiy ignoring setting

### ISSUE THREAD

**Issue by KnKay** [mvisonneau/gitlab-ci-pipelines-exporter#436]
Hi,

I just try to get the Helm chart running. 
Using this as my values:

```
  redis:
    enabled: false
  config:
    gitlab:
      url: https://gitlab.****
      token: <token>
      enable_tls_verify: false
    wildcards:
      - {}
```

I still get an error for a self signed cert.
Am I doing something wrong? I want to prevent a solution, where I build a container with our cert chain and fork the helm chart. 

Cheers!

Kay!
