### ISSUE TITLE
config file definitions not working

### ISSUE THREAD

**Issue by varn0** [mvisonneau/gitlab-ci-pipelines-exporter#448]
Hello, I haven't been able to start the exporter, looks like it's not reading the `config.yml` correctly.
This is my config file:
```yml
config:
  log:
    level: debug
  gitlab:
    url: http://my-self-hosted.gitlab-server.com
    token: ***********
  projects:
    - name: python-projects/test-python-packages
  wildcards:
    - owner: {name: python-projects, kind: group}
```
This is how I first started the exporter container and the output:
```bash
docker run -it \                                                    
   --name gitlab-ci-pipelines-exporter \
   -v $(pwd)/config.yml:/etc/config.yml \
   -p 8080:8080 \
   --network gitlab-net \
   mvisonneau/gitlab-ci-pipelines-exporter:v0.5.3 \
   run --config /etc/config.yml
ERRO[0000] Key: 'Config.Gitlab.Token' Error:Field validation for 'Token' failed on the 'required' tag
Key: 'Config.Projects' Error:Field validation for 'Projects' failed on the 'at-least-1-project-or-wildcard' tag
Key: 'Config.Wildcards' Error:Field validation for 'Wildcards' failed on the 'at-least-1-project-or-wildcard' tag 
```
Then did this and the token error went away:
```bash
docker run -it \                                                    
   --name gitlab-ci-pipelines-exporter \
   -v $(pwd)/config.yml:/etc/config.yml \
   -p 8080:8080 \
   --network gitlab-net \
   mvisonneau/gitlab-ci-pipelines-exporter:v0.5.3 \
   run --config /etc/config.yml --gitlab-token **************
ERRO[0000] Key: 'Config.Projects' Error:Field validation for 'Projects' failed on the 'at-least-1-project-or-wildcard' tag
Key: 'Config.Wildcards' Error:Field validation for 'Wildcards' failed on the 'at-least-1-project-or-wildcard' tag 
```

I'm using `gitlab/gitlab-ce:14.8.0-ce.0`
