### ISSUE TITLE
Error: invalid header field value \"Bearer xxxxxxxxxx\\n\"

### ISSUE THREAD

**Issue by djstocum50** [mvisonneau/gitlab-ci-pipelines-exporter#449]
## Error
I'm seeing this error in my POD log "Error: invalid header field value \"Bearer xxxxxxxxxx\\n\".  It looks like there is an extra line being added at the end of the bearer token in the Get HEADER call.  I can't authenticate to my Gitlab instance because of this.

## Description
I'm doing a helm install of gitlab-ci-pipelines-exporter on a Kubernetes cluster.  I'm using base64 to encrypt the $GCPE_GITLAB_TOKEN and I pass this as a secret and call it in the /etc/config.yml file in my ConfigMap.  Is the "\n" (extra line) a bug or misconfiguration in my config.yml file?  How can I get around this error that I am seeing in my log?  Below is the config.yml file that I am passing.

```yaml
data:
  config.yml: |-
    log:
      format: json
    gitlab:
      url: https://gitlab.widget.com
      token: $GCPE_GITLAB_TOKEN
      enable_health_check: true
      enable_tls_verify: true
    projects:
      - name: project1/pipeline
      - name: project2/pipeline
      - name: project3/pipeline
      - name: project4/pipeline
 ```
## Log
```
{"error":"Get \"https://gitlab.widget.com/api/v4/projects/project1/repository/branches?page=1\u0026per_page=100\": net/http: invalid header field value \"Bearer **************\\n\" for key Authorization","level":"warning","msg":"pulling refs from project","project-name":"project1","time":"2022-05-06T20:20:28Z"}
