### ISSUE TITLE
feature request: wilcard for any 'owner' and specific 'kind'

### ISSUE THREAD

**Issue by weakcamel** [mvisonneau/gitlab-ci-pipelines-exporter#461]
To limit the number of scanned projects (to save resources and as a workaround for #397, #327 etc), I'd like to be able to scan **only** groups, not user projects, e.g.

```
gitlab:
  url: ...
wildcards:
  - kind: group
```

or 

```
gitlab:
  url: ...
wildcards:
  - owner:
      kind: group
```

This doesn't seem to be supported at the moment because according to https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/main/docs/configuration_syntax.md, owner `name` is mandatory and you can't specify a regexgp.

It would be really super useful to have such option for larger Gitlab instances
- it's quite typical to NOT include users' personal projects in public metrics
- the alternative is to specify all the existing Gitlab group with `kind: group` option which doesn't really make much practical sense -  "owner" is either a group or user and that's something permanent and unlikely to change
