### ISSUE TITLE
Webhook lookup can't find a project in a subgroup

### ISSUE THREAD

**Issue by cebidhem** [mvisonneau/gitlab-ci-pipelines-exporter#510]
Hey there,

I'm trying to use metrics push instead of pull, the idea being to give the ability to our developers to use or not the webhook to retrieve statistics about their pipelines.

Here is my config (shorten for brevity):
```
    config:
      server:
        enable_pprof: false
        listen_address: :8080
        metrics:
          enable_openmetrics_encoding: false
          enabled: true
        webhook:
          enabled: true
      wildcards:
      - owner:
          include_subgroups: true
          kind: group
          name: breima
```

And in the logs, I can see the following:
```
{"ip-address":"redacted_ip:43386","level":"debug","msg":"webhook request","time":"2022-08-24T16:15:23Z","user-agent":"GitLab/15.4.0-pre"}
{"level":"debug","msg":"project ref not matching wildcard, skipping..","project-name":"breima/devops/infra/tf-main","ref":"develop","ref-kind":"branch","time":"2022-08-24T16:15:23Z"}
{"level":"info","msg":"done looking up for wildcards matching the project ref","project-name":"breima/devops/infra/tf-main","ref":"develop","ref-kind":"branch","time":"2022-08-24T16:15:23Z"}
```

If I understood correctly the config, with the wildcard I've set up, this project - which is in a subgroup of the owner `breima` - should be looked up right ? Or did I miss something here ?
