### ISSUE TITLE
docker deployment issues: "could not find any pipeline"

### ISSUE THREAD

**Issue by oregonpillow** [mvisonneau/gitlab-ci-pipelines-exporter#513]
Hi,
i'm not understanding the config setup. I simply want to display all pipeline/job related data within grafana for a self-hosted instance (including all branches).

Within the docker logs i see this message:

`msg="discovered new ref"` for each branch which suggests it can read the data ok. However, then i get these messages for each branch:

`"could not find any pipeline for the ref" project-name=<redacted project name>? ref=0.0.1 ref-kind=tag`

i don't know what this is supposed to mean, or what ref=0.0.1 has to do with anything?
If you could provide me the correct yaml i should use i would greatly appreciate it.

```
---
log:
  level: debug

gitlab:
  url: <redacted>
  token: <redacted>

# Pull jobs related metrics on all projects
project_defaults:
  pull:
    refs:
      branches:
        regexp: .*
      merge_requests:
        enabled: true

# Example public projects to monitor
projects:
  - name: <redacted>
    pull:
      environments:
        enabled: true

```
thanks for any help, would be awesome to get this working!
