### ISSUE TITLE
Readiness probe failed for gitlab.com

### ISSUE THREAD

**Issue by doroshenko-dev** [mvisonneau/gitlab-ci-pipelines-exporter#562]
I have deployed the Helm chart using the `gitlab.com` endpoint
```
config:
  gitlab:
    url: https://gitlab.com/
    token: $GCPE_GITLAB_TOKEN
```
and readiness probe always fails when the exporter is polling the projects correctly.
Also, I have checked the liveness endpoint `/health/live` status 200 OK when `/health/ready` status 503 Service Unavailable.
Any idea what could be wrong?

Thank you.
