### ISSUE TITLE
Gitlab CI/CD Analytics metrics for pipeline does not match with metrics exported by gitlab-ci-pipelines-exporter

### ISSUE THREAD

**Issue by adeelahmadch** [mvisonneau/gitlab-ci-pipelines-exporter#564]
**Description:**
We are seeing a difference between **Gitlab CI/CD Analytics metrics** and metrics exported by **gitlab-ci-pipelines-exporter**. 
For example, GitLab "**Pipelines charts**" for a project shows us **"all, success"** pipelines count over a day. Which does not match with;
```
count(rate(gitlab_ci_pipeline_run_count{project=~"$PROJECT", ref=~"$REF"}[1m]))
```

[Pipelines charts Link](https://ibb.co/KK1Y0Q0)

The metrics shown by Gitlab Pipelines charts also match with what we see from the GitLab API. 

```
https://gitlab.example.com/api/v4/projects/2414/pipelines?updated_after=2022-11-17T00:00:00Z&updated_before=2022-11-17T23:59:59Z&status=success&per_page=10
```

**Please take a look to see if my configuration is wrong or maybe my understanding of getting the number of pipelines from `gitlab_ci_pipeline_run_count` is incorrect. Thanks in advance.**  

- **Gitlab-ci-pipelines-exporter version**: [v0.5.4](https://hub.docker.com/layers/mvisonneau/gitlab-ci-pipelines-exporter/v0.5.4/images/sha256-61e0ffd051b73f76da3302f62a24b1d6264abb0ceef56465a3c197b0168bb691?context=explore)

- **Gitlab version**: 15.4.1

- **Configuration**:

```
log:
  level: info

gitlab:
  url: https://gitlab.example.com
  token: "**********************"

# redis:
#  url: "redis://gitlab-ci-pexporter-cache.example.com:6379"

server:
  webhook:
    enabled: true
    secret_token: "***************************"

project_defaults:
  pull:
    environments:
      enabled: true
    refs:
      branches:
        regexp: ".*"
        most_recent: 0
        max_age_seconds: 172800
      merge_requests:
        enabled: true
        most_recent: 0
        max_age_seconds: 172800
      tags:
        regexp: ".*"
        most_recent: 0
        max_age_seconds: 172800
        exclude_deleted: true
    pipeline:
      jobs:
        enabled: true
        from_child_pipelines:
          enabled: true
        runner_description:
          enabled: true
      variables:
        enabled: true

pull:
  projects_from_wildcards:
    on_init: false
    scheduled: false

  environments_from_projects:
    on_init: true
    scheduled: true

  refs_from_projects:
    on_init: true
    scheduled: true

  metrics:
    on_init: false
    scheduled: false


projects:
  - name: example-dot-com/infrastructure/project1
  - name: example-dot-com/infrastructure/project2
  - name: example-dot-com/infrastructure/project3
  - name: example-dot-com/development/project4
  - name: example-dot-com/others/project5
```
