### ISSUE TITLE
Wildcard branch regexp does not work 

### ISSUE THREAD

**Issue by OmegaM** [mvisonneau/gitlab-ci-pipelines-exporter#607]
We used k8s for deploy exporter, and want to get metrics of all pipelines on all brunches, but it does not work.
Default value for wildcards.pull.refs.branches.regexp is '^main|master$', I was trying  to use '*', '.*', and also 'BRANCH_TYPE.*|ANOTHER_BRANCH_TYPE.*' and it does not  work, only main and master regexp is working

Part of config file:
```yaml
config: 
  gitlab:
    url: xxx
    enable_health_check: false
    enable_tls_verify: false
  wildcards:
    - owner: 
        name: 'group/subgroup1'
        kind: group
        include_subgroups: true
        pull:
          refs:
            branches:
              enabled: true
              regexp: ".*"
            tags:
              enabled: false
    - owner: 
        name: 'group/subgroup2'
        kind: group
        include_subgroups: true
        pull:
          refs:
            branches:
              enabled: true
              regexp: ".*"
            tags:
              enabled: false
```
Result:
I still getting tags
```bash
k logs exporter-gitlab-ci-pipelines-exporter-777759b6bf-9fw7r | grep '"ref-kind":"tag"' | wc -l
   10104
```
I've got 31 projects in gitlab (I can see them from prometheus)
```bash
k logs exporter-gitlab-ci-pipelines-exporter-777759b6bf-9fw7r | grep '"ref-kind":"branch"' | wc -l 
      76
```
