### ISSUE TITLE
Use Job events webhook to processes job updates

### ISSUE THREAD

**Issue by aaronborden-rivian** [mvisonneau/gitlab-ci-pipelines-exporter#618]
We're collecting jobs data as well as pipeline data. We have many events per minute and even with 20 api requests per second, the number of queued tasks  remains high. We think that using the [Job events webhook](https://docs.gitlab.com/ee/user/project/integrations/webhook_events.html#job-events) will reduce the need for additional data fetches and speed up the time to process events.

```yaml
          maximum_requests_per_second: 20
          project_defaults:
            pipeline:
              jobs:
                enabled: true
                from_child_pipelines:
                  enabled: true
```
