### ISSUE TITLE
Tags are scraped even when set to disabled 

### ISSUE THREAD

**Issue by sharkymcdongles** [mvisonneau/gitlab-ci-pipelines-exporter#632]
```
  config:
      gitlab:
        url: http://gitlab-webservice-default.gitlab.svc.cluster.local:8181
        enable_health_check: true
        enable_tls_verify: false
        maximum_requests_per_second: 7
      pull:
        environments_from_projects:
          on_init: false
          scheduled: false
      project_defaults:
        output_sparse_status_metrics: true
        pull:
          environments:
            enabled: false
        refs:
          branches:
            enabled: true
            regexp: "^(master|development|release)$"
            most_recent: 10
            max_age_seconds: 0
            exclude_deleted: true
          merge_requests:
            enabled: false
          tags:
            enabled: false
        pipeline:
          jobs:
            enabled: false
          from_child_pipelines:
            enabled: false
          runner_description:
            enabled: true
          variables:
            enabled: false

```

Is something wrong with my config or is the tags enabled false not working properly?

**Comment by arnaudlemaignen** [comment]
I had the same issue and even if I was requesting a subset of tags using regex, I was still getting the whole list.
In the end I found out that it was the redis DB that was not cleaned
killing the  "gitlab-ci-pipelines-exporter-redis-master-0" pod and restart the exporter fixed the issue.

**Comment by tan-wei-xin-alez** [comment]
same problem running [example/quickstart/docker-compose.yml](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/main/examples/quickstart/docker-compose.yml) with the following `gitlab-ci-pipelines-exporter.yml`
```
---
log:
  level: debug

gitlab:
  url: https://gitlab.com
  token: <gitlab_personal_access_token>

# https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/main/docs/configuration_syntax.md
project_defaults:
  pull:
    refs:
      enabled: true
      regexp: "^(?:main|develop)$"
    tags:
      enabled: false
    merge_requests:
      enabled: true

projects:
  - name: <project_name>
```

**Comment by tewfik-ghariani** [comment]
@tan-wei-xin-alez  I believe the `tags` property should be in the `refs` subtree

**Comment by tan-wei-xin-alez** [comment]
oh that's embarrassing σ(^_^;) I was also missing the `branches` key (p_-)

seems to work now with the following config
```
---
log:
  level: debug

gitlab:
  url: https://gitlab.com
  token: <gitlab_personal_access_token>

# https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/main/docs/configuration_syntax.md
project_defaults:
  pull:
    refs:
      branches:
        enabled: true
        regexp: "^(?:main|develop)$"
      tags:
        enabled: false
      merge_requests:
        enabled: true

projects:
  - name: <project_name>
```
