### ISSUE TITLE
Helm Chart - monitor/ exporter issues

### ISSUE THREAD

**Issue by stefanjay** [mvisonneau/gitlab-ci-pipelines-exporter#667]
I use the default helm chart with following coniguration:

```
      envVariables:
        - name: GCPE_INTERNAL_MONITORING_LISTENER_ADDRESS
          value: tcp://127.0.0.1:8082
```

When I try the CLI in the pod:

```
/ $ gitlab-ci-pipelines-exporter monitor

FATA[0000]                                               error="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp: address tcp://127.0.0.1:8082: too many colons in address\""

```

Also the metrics did not work but the access_token is correct and tested with curl against the gitlab api. 

```
      config:
        # # Complete configuration syntax reference available here:
        # # https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/master/docs/configuration_syntax.md
        gitlab:
          url: http://gitlab-webservice-default.gitlab.svc.cluster.local:8080/
          token: glpat-7bqGyWPodxxxxxxxx
          enable_tls_verify: false

          health_url: http://gitlab-webservice-default.gitlab.svc.cluster.local:8080/-/health
          enable_health_check: true
        # projects:
        #   - name: gitlab-instance-89f24a72/gitlab-exporter-test-project
        #   - name: gitlab-instance-89f24a72/Monitoring
        wildcards:
          - owner:
              name: root
              kind: user
```

I added a scrape config to prometheus but get no metrics.
