### ISSUE TITLE
Topics are not populated

### ISSUE THREAD

**Issue by lcostea** [mvisonneau/gitlab-ci-pipelines-exporter#697]
I added a topic (terraform) to our Gitlab project and the project is in the list of projects to monitor and it does appear in the metrics. But I don't see the topics being populated.
<img width="510" alt="Screenshot 2023-08-10 at 11 06 44" src="https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/assets/1910380/d9127f78-6e5a-4aaa-b513-d2d0e7e59303">
<img width="1268" alt="Screenshot 2023-08-10 at 11 07 26" src="https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/assets/1910380/ded7fd9c-6772-4605-b704-3e60c398ab33">
The config is like this:
```
  config:
    log:
      level: debug
    gitlab:
      url: https://gitlab.com
    pull:
      projects_from_wildcards:
        scheduled: true
        interval_seconds: 18000
      environments_from_projects:
        scheduled: true
        interval_seconds: 3600
      refs_from_projects:
        scheduled: true
        interval_seconds: 3600
      metrics:
        scheduled: true
        interval_seconds: 150
    project_defaults:
      pull:
        environments:
          enabled: true
        refs:
          branches:
            enabled: false
          tags:
            most_recent: 20
          merge_requests:
            most_recent: 20
    garbage_collect:
      projects:
        # Whether or not to trigger a garbage collection of the
        # projects when the exporter starts (optional, default: false)
        on_init: true
      environments:
        # Whether or not to trigger a garbage collection of the
        # environments when the exporter starts (optional, default: false)
        on_init: true
      refs:
        # Whether or not to trigger a garbage collection of the
        # projects refs when the exporter starts (optional, default: false)
        on_init: true
      metrics:
        # Whether or not to trigger a garbage collection of the
        # metrics when the exporter starts (optional, default: false)
        on_init: true
    projects:
      - name: [.....]/access-management
```
Any ideas what I am doing wrong and what else I could try?
I think the Gitlab API called is List all projects https://docs.gitlab.com/ee/api/projects.html#list-all-projects for the authenticated user (token), so it is a big list which will be returned, which makes it hard to check if Gitlab actually returns the topics for my project, but for other projects (returned in the list all projects API call) it does.

**Comment by usine4sigma** [comment]
I still have this issue too.
I can't manage to get topics from my projects.
I'm using Helm chart 0.5.10.
EDIT: I also tried with 0.6.0, same issue.
I took a look at : 
- https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/issues/282
- https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/pull/887
- https://github.com/HO-CTO/gitlab-ci-pipelines-exporter/pull/1

Here's my config : 

```
config:
  gitlab:
    url: TEST
    enable_health_check: true
    enable_tls_verify: true
    maximum_requests_per_second: 2
  pull:
    metrics:
      on_init: false
      scheduled: true
      interval_seconds: 600
    projects_from_wildcards:
      on_init: false
      scheduled: true
      interval_seconds: 540 # 15 min
    environments_from_projects:
      on_init: false
      scheduled: true
      interval_seconds: 86400
    refs_from_projects:
      on_init: false
      scheduled: true
      interval_seconds: 14400
  garbage_collect:
    projects:
      on_init: false
      scheduled: true
      interval_seconds: 86400
    environments:
      on_init: false
      scheduled: true
      interval_seconds: 86400
    refs:
      on_init: false
      scheduled: true
      interval_seconds: 14400
    metrics:
      on_init: false
      scheduled: true
      interval_seconds: 600
  project_defaults:
    output_sparse_status_metrics: true
    pull:
      refs:
        from:
          pipelines:
            enabled: true
            depth: 10
        branches:
          enabled: true
          regexp: "^(main|master|develop|\\d+\\.\\d+\\.\\d+.*)$"
          exclude_deleted: true
          most_recent: 3
          max_age_seconds: 604800
      environments:
        enabled: true
        exclude_stopped: true
      pipeline:
        depth: 5
        jobs:
          enabled: true
        from_child_pipelines:
          enabled: true
        variables:
          enabled: false
        runner_description:
          enabled: false
      tags:
        enabled: false
      merge_requests:
        enabled: true
        max_age_seconds: 10800
  wildcards:
    - archived: false
      membership: true

env:
  - name: GCPE_LOG_LEVEL
    value: "info"
  - name: GCPE_WORKER_COUNT
    value: "1"

replicas: 1

nodeSelector:
  agentpool: npuser

gitlabSecret: "gitlab-ci-pipelines-exporter-token"

redis:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/redis
    tag: "7.2.4"
    pullPolicy: IfNotPresent
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 2Gi
    nodeSelector:
      agentpool: npuser
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  replica:
    replicaCount: 0
    persistence:
      enabled: true
      size: 2Gi
    nodeSelector:
      agentpool: npuser
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 2000m
    memory: 2Gi

readinessProbe:
  httpGet:
    path: /metrics
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 10

livenessProbe:
  httpGet:
    path: /health/live
    port: 8080
  initialDelaySeconds: 120
  periodSeconds: 60
  failureThreshold: 5

``` 

What am I doing wrong ?
Any ideas ?
Someone else have this issue too ?

Thanks a lot for your help !
