### ISSUE TITLE
webhook with error 

### ISSUE THREAD

**Issue by aloisiobilck** [mvisonneau/gitlab-ci-pipelines-exporter#727]
When trying to use the webhook, I see this error in the log.
```
{"ip-address":"10.6.0.96:37224","level":"debug","msg":"webhook request","time":"2023-10-04T13:50:43Z","user-agent":"GitLab/16.3.4-ee"}
{"error":"context canceled","level":"error","msg":"reading ref from the store","project-name":"group/frontend","ref":"aloisio-test1","ref-kind":"branch","time":"2023-10-04T13:50:43Z"}
```

Below is the configuration of my helm chart
```
config:
  log:
    level: debug
  gitlab:
    url: https://gitlab.mycompany.com
    token: <token>
    enable_health_check: false
    enable_tls_verify: true

  server:
    enable_pprof: true
    webhook:
      enabled: true
      secret_token: <token>

  pull:
    projects_from_wildcards:
      on_init: false
      scheduled: false

    environments_from_projects:
      on_init: false
      scheduled: false

    refs_from_projects:
      on_init: false
      scheduled: false

    metrics:
      on_init: false
      scheduled: false

  projects:
    - name: group/frontend

serviceMonitor:
  enabled: true

redis:
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

ingress:
  enabled: true
  hosts:
    - gitlab-ci-pipelines-exporter.mycompany.com
```
Gitlab webhook status:
![image](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/assets/18704073/ca121d14-0595-4f9a-94e6-1e2bee37b30e)

Am I doing something wrong?

**Comment by vladimirblahoz** [comment]
I have very similar helm values and exactly the same error. One more info - when the scheduled pulls are enabled, they work just fine on this configuration.

**Comment by aloisiobilck** [comment]
In the gitLab VM, CPU consumption is high when I enable pulls

```
config:
  gitlab:
    url: https://gitlab.mycompany.com
    token: <token>
    enable_health_check: false
    enable_tls_verify: false
    maximum_jobs_queue_size: 1000
    maximum_requests_per_second: 1
    burstable_requests_per_second: 5

  server:
    enable_pprof: true
    webhook:
      enabled: true
      secret_token: <token>

  pull:
    projects_from_wildcards:
      on_init: false
      scheduled: false

    environments_from_projects:
      on_init: false
      scheduled: false

    refs_from_projects:
      on_init: false
      scheduled: true
      interval_seconds: 300

    metrics:
      on_init: false
      scheduled: true
      interval_seconds: 300

  project_defaults:
    pull:
      refs:
        branches:
          enabled: true
          regexp: "^(?:main|release)$"
        tags:
          enabled: false
        # merge_requests:
        #   enabled: true
        #   most_recent: 10
      pipeline:
        jobs:
          enabled: true
          from_child_pipelines:
            enabled: true

  projects:
    - name: test/apigateway
    - name: test/ops
      pull:
        refs:
          branches:
            enabled: true
            regexp: "^(?:.*-main|release|clean-db-mssql|general-.*)$"
    - name: test/installation
      pull:
        refs:
          tags:
            enabled: true

serviceMonitor:
  enabled: true

redis:
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

ingress:
  enabled: true
  hosts:
    - gitlab-ci-pipelines-exporter.mycompany.com
```
