### ISSUE TITLE
Merge Requests Not Pulling Most Recent

### ISSUE THREAD

**Issue by geCarlo** [mvisonneau/gitlab-ci-pipelines-exporter#757]
Hi, big fan of this tool.

I am currently facing an issue with tracking merge request pipelines where the `most_recent` attribute doesn't give me what I would expect. With the following config defined in my `gitlab-ci-pipelines-exporter.yml`:
```
projects:
  - name: <project-name>
    pull:
      refs:
        branches:
          enabled: false
        tags:
          enabled: false
        merge_requests:
          enabled: true
          most_recent: 10
      pipeline:
        jobs:
          enabled: false
          from_child_pipelines:
            enabled: false
```
I am not receiving MR pipelines that have been updated recently (for instance, I have a test MR open that I am updating on the fly and am not seeing it when I query from Prometheus). I do indeed get 10 merge request pipelines from the config above, however, many of them are months old with some of them even being closed. This project has many MRs updated daily, so I would not expect to see MR pipelines that are so old. Has this issue been seen before? Please let me know if I can provide more info.
