### ISSUE TITLE
Unable to get GCPE to display non master/main branches on Grafana dashboard

### ISSUE THREAD

**Issue by ghostx31** [mvisonneau/gitlab-ci-pipelines-exporter#787]
Hi, I have setup GCPE on our GKE cluster along with our self-hosted Gitlab. 
Here is the current configuration: 
```yaml
project_defaults:
  output_sparse_status_metrics: true
  pull:
    environments:
      enabled: true
      regexp: ".*"
    refs:
      branches:
        enabled: true
        regexp: ".*"
        most_recent: 0
        max_age_seconds: 0
      tags:
        enabled: true
        regexp: ".*"
        most_recent: 0
        max_age_seconds: 0
        exclude_deleted: true
      merge_requests:
        enabled: true
        most_recent: 0
        max_age_seconds: 0
```

As per my understanding, since I have set `project_defaults.pull.refs.branches.regexp` to `.*`, it should pull all refs from the projects it detects but it doesn't seem to be the case and it is only pulling pipelines which are running from master branches. Am I missing something?

Thanks in advance!
