### ISSUE TITLE
Missing job metrics (enabled in config)

### ISSUE THREAD

**Issue by tony-engineering** [mvisonneau/gitlab-ci-pipelines-exporter#790]
Hi, I tried to setup the exporter using Helm, and I am missing metrics for jobs. 
I searched in the issues here and saw similar issues without clear solution. 
I checked in my config that I enabled the export of jobs metrics, but that didnt help. When I go to Prometrheus UI, and search for "gitlab_ci_", I can only see "gitlab_ci_pipelines". I would expect to see "gitlab_ci_job_..."
![image](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/assets/9582205/2baa27dc-f986-4b19-89ad-347c4e644ace)

Here is my config
```
config:
  gitlab:
    url: https://gitlab.com
    # You can also configure the token using --gitlab-token
    # or the  environment variable
    token: <token>
  wildcards:
  - {}
  projects:
    - name: org/mint
  project_defaults:
    output_sparse_status_metrics: true
    pull:
      environments:
        enabled: false
        regexp: ".*"
        exclude_stopped: true
      refs:
        branches:
          enabled: true
          regexp: "^main|master$"
          most_recent: 0
          max_age_seconds: 0
          exclude_deleted: true
        tags:
          enabled: true
          regexp: ".*"
          most_recent: 0
          max_age_seconds: 0
          exclude_deleted: true
        merge_requests:
          enabled: false
          most_recent: 0
          max_age_seconds: 0
      pipeline:
        jobs:
          enabled: true
          from_child_pipelines:
            enabled: false
          runner_description:
            enabled: true
            aggregation_regexp: shared-runners-manager-(\d*)\.gitlab\.com
        variables:
          enabled: false
          regexp: ".*"
```

Can you help me here ?
Thanks

**Comment by tony-engineering** [comment]
Somehow some additional metrics showed up after I uninstall / reinstall the chart multiple times ... I tried to rollback and the metrics are still shown, weird

**Comment by sebglon** [comment]
I have the same. No Job metrics are generated
here is my config:
```
      project_defaults:
        refs:
          regexp: ".*"
        pull:
          refs:
            tags:
              enabled: false
            merge_requests:
              enabled: true
              max_age_seconds: 10800 # 3h
        pipeline:
          jobs:
            enabled: true
            runner_description:
              enabled: false
      wildcards:
        - owner:
            name: ubbleai
            kind: group
          pull:
            refs:
              tags:
                enabled: false
              merge_requests:
                enabled: true
                max_age_seconds: 10800 # 3h
            pipeline:
              jobs:
                enabled: true
                runner_description:
                  enabled: false
```
