### ISSUE TITLE
api call limit and remaining == 0

### ISSUE THREAD

**Issue by sereinity** [mvisonneau/gitlab-ci-pipelines-exporter#798]
Hello,

Versions:
- chart: 0.3.2 (but the bug is also valid for 0.3.1) 
- app: v0.5.6 (and bug also present in v0.5.5)

Endpoint: gitlab.com

values.yaml:
```yaml
config:
  garbage_collect:
    metrics:
      on_init: true
    refs:
      on_init: true
  projects:
    - name: redacted1
    - name: redacted2
    - name: redacted3
gitlabSecret: gitlab-exporter-token
serviceMonitor:
  enabled: true
```

After a pod restart, the metrics `gcpe_gitlab_api_requests_limit` and `gcpe_gitlab_api_requests_remaining` are solid `0`.

Before, the limit was at `2000`.

The working pod was started on Feburary 7th, and terminated the 17th. Since I tried to purge redis, restarted … I got metrics and obviously the API with gitlab works, but the limits/remaining metrics stay at `0`.

I believe that gcpe fetch the api limits at start time? maybe gitlab changed their API and this information disappeared?

This issue is annoying because I have an alert on remaining calls, (I will adapt the alert to stop screaming if limit == 0).
