### ISSUE TITLE
Many pipelines not displayed

### ISSUE THREAD

**Issue by Alex7851** [mvisonneau/gitlab-ci-pipelines-exporter#827]
We have thousends pipelines in our gitlab.
Me exclude jobs, environments data and increase refresh intervals but problem about not displaying some many pipelines is actual.

Its not a problem with some projects because i see some pipes from project and same pipes from this projects don't displayed and its still have existing branches, not removed (after merge or smth).

I suppose it's about big data from Gitlab. I see about 300-400 pipes in PIPELINES panel but we have several thousends pipes

My current config is:

```
gitlab:
  url: 'gitlab instance url'
  token: 'mytoken'

wildcards:
  - 
    pull:
          refs:
            branches:
              regexp: ^.*$
    
pull:
  pipelines:
    enabled: true
    on_init: true
    refs:
      regexp: ^.*$
  projects_from_wildcards:
    on_init: true
    scheduled: true
    interval_seconds: 3600

  environments_from_projects:
    on_init: false
    scheduled: false

  refs_from_projects:
    on_init: true
    scheduled: true
    interval_seconds: 900

  metrics:
    on_init: true
    scheduled: true
    interval_seconds: 180

project_defaults:
  pull:
    pipeline:
      jobs:
        enabled: false
metrics:

  pipeline:
    enabled: true
  job:
    enabled: false
  lint:
    enabled: false
  project:
    enabled: false
  group:
    enabled: false
```

How can i improove this config to see all pipes in gitlab without omitted pipelines?
