### ISSUE TITLE
pulling metrics from all branches

### ISSUE THREAD

**Issue by Mrsenior12** [mvisonneau/gitlab-ci-pipelines-exporter#841]
I have following configuration in `gitlab-ci-pipeline-exporter.yml`

```
project_defaults:
  pull:
    pipeline:
      jobs:
        enabled: true
  refs:
    branches:
      enable: true
```
Following configuration fetch metrics only from `main` branch.
Is there a method to fetch all branches from all projects?
