### ISSUE TITLE
Gitlab CI exporter stop pulling new metrics

### ISSUE THREAD

**Issue by huyhoang8398** [mvisonneau/gitlab-ci-pipelines-exporter#866]
![image](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/assets/25379882/980b0307-5b3a-4425-8812-92a6bd1c4dae)
after a certain time ( or first run im not sure ), it stops pulling new metrics:

here is my config

```yml
---
log:
  level: info

gitlab:
  url: https://x
  token: x
  maximum_jobs_queue_size: 5000
# Pull jobs related metrics on all projects
project_defaults:
  pull:
    pipeline:
      jobs:
        enabled: true
projects:
  - name: foo/bar
  - name: foo/bar
  ```
