### ISSUE TITLE
Readiness probe failed: HTTP probe failed with statuscode: 503

### ISSUE THREAD

**Issue by ynsdll** [mvisonneau/gitlab-ci-pipelines-exporter#916]
I have found issues about statuscode: 503. There is an offer that adding trailing slash at the end of `config.gitlab.url` but it doesnt affect me. I am always getting 503 and pod waiting Running 0/1 status

values.yaml

```
# config -- configuration of the exporter
config:
  log:
    level: info
  gitlab:
    url: https://gitlab.com/
    maximum_requests_per_second: 1
    burstable_requests_per_second: 5
    maximum_jobs_queue_size: 10000
  pull:
    metrics:
      interval_seconds: 120
  project_defaults:
    pull:
      environments:
        enabled: true
      pipeline:
        jobs:
          enabled: true
  projects:
    - name: backend/auth-api
    - name: backend/b2b-api
    - name: backend/b2b-api-gateway
    - name: backend/backoffice-api
    - name: backend/backoffice-graphql
    - name: backend/balance-api
    - name: backend/bank-settlement-api
    - name: backend/chatbot-api
    - name: backend/config-server
```
