### ISSUE TITLE
disable tags not working

### ISSUE THREAD

**Issue by ynsdll** [mvisonneau/gitlab-ci-pipelines-exporter#920]
I am trying to disable tags. My config is below. Even if tags.enabled is false, exporter try to get tag metrics

logs;

```
{"gitlab-endpoint":"https://gitlab.com","gitlab-rate-limit":"5rps","level":"info","msg":"configured","time":"2024-10-10T15:48:53Z"}
{"level":"info","msg":"pull projects from wildcards","on-init":"yes","scheduled":"every 1800s","time":"2024-10-10T15:48:53Z"}
{"level":"info","msg":"pull environments from projects","on-init":"yes","scheduled":"every 1800s","time":"2024-10-10T15:48:53Z"}
{"level":"info","msg":"pull refs from projects","on-init":"yes","scheduled":"every 300s","time":"2024-10-10T15:48:53Z"}
{"level":"info","msg":"pull metrics","on-init":"yes","scheduled":"every 120s","time":"2024-10-10T15:48:53Z"}
{"level":"info","msg":"garbage collect projects","on-init":"no","scheduled":"every 14400s","time":"2024-10-10T15:48:53Z"}
{"level":"info","msg":"garbage collect environments","on-init":"no","scheduled":"every 14400s","time":"2024-10-10T15:48:53Z"}
{"level":"info","msg":"garbage collect refs","on-init":"no","scheduled":"every 1800s","time":"2024-10-10T15:48:53Z"}
{"level":"info","msg":"garbage collect metrics","on-init":"no","scheduled":"every 600s","time":"2024-10-10T15:48:53Z"}
{"level":"info","msg":"redis url configured, initializing connection..","time":"2024-10-10T15:48:53Z"}
{"level":"info","msg":"connected to redis","time":"2024-10-10T15:48:53Z"}
{"level":"info","msg":"scheduling environments from projects pull","projects-count":7,"time":"2024-10-10T15:48:53Z"}
{"level":"info","msg":"scheduling refs from projects pull","projects-count":7,"time":"2024-10-10T15:48:53Z"}
{"host":"127.0.0.1:8082","level":"info","msg":"internal monitoring listener set","path":"","scheme":"tcp","time":"2024-10-10T15:48:53Z"}
{"level":"warning","msg":"GitLab health check has been disabled. Readiness checks won't be operated.","time":"2024-10-10T15:48:53Z"}
{"controller-uuid":"ab8316d9-1a8d-45e4-b271-7312767b4b24","level":"info","listen-address":":8080","metrics-endpoint-enabled":true,"msg":"http server started","openmetrics-encoding-enabled":false,"pprof-endpoint-enabled":false,"time":"2024-10-10T15:48:53Z","webhook-endpoint-enabled":false}

{"environments-count":18,"level":"info","msg":"scheduling metrics pull","refs-count":494,"time":"2024-10-10T15:48:53Z"}

{"level":"info","msg":"scheduling projects from wildcards pull","time":"2024-10-10T15:48:53Z","wildcards-count":0}
```

configuration

```
# config -- configuration of the exporter
config:
  log:
    level: info
  gitlab:
    url: https://gitlab.com
    enable_health_check: false
    maximum_requests_per_second: 5
    burstable_requests_per_second: 25
    maximum_jobs_queue_size: 10000
  pull:
    metrics:
      interval_seconds: 120
  project_defaults:
    pull:
      environments:
        enabled: true
      refs:
        branches:
          enabled: true
          regexp: "^(?:main|master|develop)$"
        tags:
          enabled: false
      pipeline:
        jobs:
          enabled: false
  projects:
    - name: graphql-response-samples
    - name: android
    - name: firebase-hosting
    - name: ios
    - name: backoffice
    - name: identity-verification
    - name: web
```
