### ISSUE TITLE
Not all refs (Tags/MRs) are exported 

### ISSUE THREAD

**Issue by maheshglm** [mvisonneau/gitlab-ci-pipelines-exporter#940]
I am using `webhook` approach, and here is the configuration I used. I expect, latest 10 recent tags and 5 recent branches should get polled, but its not working as expected. Pulling random MRs (not latest 5) and same goes to Tags as well (not latest 10).

Noticed similar behaviour with pull based approach as well, where expecting latest 10 merge-requests, but seeing random MRs

```
  wildcards:
    - {}
   
  project_defaults:
    output_sparse_status_metrics: true
    pull:
      pipeline:
        jobs:
          enabled: true
          from_child_pipelines:
            enabled: true
          aggregation_regexp: ".*"
        variables:
          enabled: false
      refs:
        branches:
          enabled: true
          most_recent: 0
          regexp: "^(?:main|master)$"
          # If the age of the most recently updated pipeline for the branch is greater than
          # this value, the pipeline metrics won't get exported (optional, default: 0 (disabled))
          max_age_seconds: 0
        tags:
          enabled: true
          regexp: ".*"
          most_recent: 10
          # If the age of the most recently updated pipeline for the tag is greater than
          # this value, the pipeline metrics won't get exported (optional, default: 0 (disabled))
          max_age_seconds: 0
          exclude_deleted: true
        merge_requests:
          enabled: true
          most_recent: 5
          # If the age of the most recently updated pipeline for the merge request is greater than
          # this value, the pipeline metrics won't get exported (optional, default: 0 (disabled))
          max_age_seconds: 0
```
