### ISSUE TITLE
Minimal configuration to track pipelines & jobs on project branch and MR with webhook

### ISSUE THREAD

**Issue by irfansofyana** [mvisonneau/gitlab-ci-pipelines-exporter#960]
Hi team, I'm currently POC of using this tool to track Gitlab CI Pipelines in my company.

Currently my config looks like this:

```yaml
gitlab:
  url: https://gitlab.mycompany.com/
  enable_health_check: true
  health_url: https://gitlab.myteksi.net/-/health
  enable_tls_verify: false
  token: ""
server:
  webhook:
    enabled: true
    secret_token: ""
pull:
  projects_from_wildcards:
    on_init: false
    scheduled: false
  environments_from_projects:
    on_init: false
    scheduled: false
  refs_from_projects:
    on_init: false
    scheduled: false
  metrics:
    on_init: false
    scheduled: false
projects:
  - path/to/project1
  - path/to/project2
```

With this configuration, it can retrieved the pipeline on master/main branch but whenever there is pipeline running on an MR it's not. 

We want to leverage webhook as much as possible to avoid too many requests to our gitlab instance.

It seems these issues are related: https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/issues/889 and https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/issues/280, but I'm still confused on what could be the most ideal setup for my use case.

Hence, creating a new issue here for easy tracking in case there is someone else having the same requirement.
