### ISSUE TITLE
Configuration to fetch all pipelines/jobs within a group through webhook

### ISSUE THREAD

**Issue by anchaubey** [mvisonneau/gitlab-ci-pipelines-exporter#961]
Hello team,

I am trying to fetch all the projects within a gitlab group which are found by webhook. I saw one of the examples:-

```
---
log:
  level: debug

gitlab:
  url: https://gitlab.com
  token: <your_token>

server:
  webhook:
    enabled: true
    secret_token: <strong_arbitrary_secret_token>

pull:
  projects_from_wildcards:
    on_init: false
    scheduled: false

  environments_from_projects:
    on_init: false
    scheduled: false

  refs_from_projects:
    on_init: false
    scheduled: false

  metrics:
    on_init: false
    scheduled: false

projects:
  # Configure a project on which you are authorized to configure webhooks
  - name: <your_project_path_with_namespace>
```

I think the above configuration limits the search to only a given project ? However, I would want to enable webhook on a group level.

could you please suggest on the same ?
