### ISSUE TITLE
Project Labels Enhancement Request

### ISSUE THREAD

**Issue by Domandrenog** [mvisonneau/gitlab-ci-pipelines-exporter#974]
### Current Behavior:

Currently, projects can only be identified by their ID, which results in losing meaningful label information.

### Proposed Enhancement:

Allow multiple labels to be assigned to each project using a nested labels structure. This would improve project organization and filtering capabilities.

## Example Configuration:

```
projects:
  - name: "676"
    labels:
      team: backend
      environment: production
      priority: high
  - name: "123"
    labels:
      team: backend2
      environment: dev
      priority: low
```
### Benefits

1. Better project organization through multiple categorization dimensions
2. Enhanced filtering and searching capabilities
3. More descriptive project metadata
4. Easier project management and identification
