### ISSUE TITLE
Inadvertantly fetching seemingly all repo's within a private hosted gitlab

### ISSUE THREAD

**Issue by bigdave777** [mvisonneau/gitlab-ci-pipelines-exporter#988]
I'm trying to set up ci pipeline exporter and the PAT I'm using appears to be granting access to all repo's within my org's gitlab.

I have the following config
```
config:
  gitlab:
    url: https://my.gitlab.com
  project_defaults:
    pull:
      refs:
        branches:
          enabled: true
        tags:
          enabled: true
        merge_requests:
          enabled: true
  pull:
    projects_from_wildcards:
      on_init: false
      scheduled: false
  projects:
    - name: foo/bar
    - name: bar/baz
```

In the logs I then see lines such as 
```
"msg":"pulling ref metrics","project-name":"something/i/dont/want/to/access
```

Is my understanding of the projects set up incorrect?

I'd previously trialled with
```
config:
  wildcards:
  - {} 
````
and that had also fetched all projects. This seems to be a limitation with the group level PAT's however I thought providing individual projects would resolve this.

Any guidance would be greatly appreciated!
